# Generated by Django 5.0.7 on 2025-01-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('cms_kor', '0001_initial'),
        ('personaggi', '0010_delete_tabellapluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tier')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
