# Generated by Django 5.0.7 on 2025-11-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_kor', '0002_tierpluginmodel'),
        ('personaggi', '0017_a_vista_attivata_inventario_manifesto_oggetto_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierpluginmodel',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_kor_tier_plugin', to='personaggi.tier'),
        ),
    ]
