# Generated by Django 4.2.4 on 2024-07-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0004_remove_spell_elemento_abilita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mattone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome del mattone')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del mattone')),
                ('aura', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='aura_mattone', to='personaggi.punteggio')),
                ('elemento', models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, related_name='elemento_mattone', to='personaggi.punteggio')),
            ],
            options={
                'verbose_name': 'Mattone',
                'verbose_name_plural': 'Mattoni',
            },
        ),
        migrations.AlterModelOptions(
            name='abilita_punteggio',
            options={'verbose_name': 'Abilità - Punteggio assegnato', 'verbose_name_plural': 'Abilità - Punteggi assegnati'},
        ),
        migrations.AlterModelOptions(
            name='abilita_requisito',
            options={'verbose_name': 'Abilità - Requisito', 'verbose_name_plural': 'Abilità - Requisiti'},
        ),
        migrations.AlterModelOptions(
            name='abilita_sbloccata',
            options={'verbose_name': 'Abilità - Tabella sbloccata', 'verbose_name_plural': 'Abilità - Tabelle sbloccate'},
        ),
        migrations.AlterModelOptions(
            name='abilita_tier',
            options={'verbose_name': 'Abilità - Tier', 'verbose_name_plural': 'Abilità - Tiers'},
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'verbose_name': 'Abilità attivata', 'verbose_name_plural': 'Abilità attivate'},
        ),
        migrations.AlterModelOptions(
            name='spell_elemento',
            options={'verbose_name': 'Spell - Elemento necessario', 'verbose_name_plural': 'Spell - Elementi necessari'},
        ),
        migrations.AlterModelOptions(
            name='tabella',
            options={'verbose_name': 'Tabella', 'verbose_name_plural': 'Tabelle'},
        ),
        migrations.AlterModelOptions(
            name='tier',
            options={'verbose_name': 'Tier', 'verbose_name_plural': 'Tiers'},
        ),
        migrations.RemoveField(
            model_name='spell',
            name='elementi',
        ),
        migrations.AlterField(
            model_name='spell',
            name='nome',
            field=models.CharField(max_length=90, verbose_name="Nome dell'abilità attivata"),
        ),
        migrations.CreateModel(
            name='spell_mattone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('valore', models.IntegerField(default=1, verbose_name='Ripetizioni del mattone')),
                ('mattone', models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.spell')),
            ],
            options={
                'verbose_name': 'Abilità attivata - Mattone necessario',
                'verbose_name_plural': 'Abilità attivate - Mattoni necessari',
            },
        ),
        migrations.AddField(
            model_name='spell',
            name='mattoni',
            field=models.ManyToManyField(help_text="Mattoni requisito dell'abilità attivata", related_name='spells', through='personaggi.spell_mattone', to='personaggi.mattone'),
        ),
    ]
