# Generated by Django 4.2.4 on 2024-07-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0005_mattone_alter_abilita_punteggio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='caratteristica',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punteggi_caratteristica', to='personaggi.punteggio', verbose_name='Carattesitica relativa'),
        ),
        migrations.AlterField(
            model_name='spell_mattone',
            name='mattone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone'),
        ),
    ]
