# Generated by Django 5.0.7 on 2025-01-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0007_alter_punteggio_options_alter_punteggio_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='abilita_prerequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('abilita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilita_prerequisiti', to='personaggi.abilita')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilita_abilitati', to='personaggi.abilita')),
            ],
            options={
                'verbose_name': 'Abilità - Prerequisito',
                'verbose_name_plural': 'Abilità - Prerequisiti',
            },
        ),
    ]
