# Generated by Django 5.0.7 on 2025-01-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0009_tabellapluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabellaPluginModel',
        ),
    ]
