# Generated by Django 5.0.7 on 2025-11-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0012_spell_aura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistica',
            fields=[
                ('punteggio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.punteggio')),
                ('valore_predefinito', models.IntegerField(default=0, help_text='Valore di default per questa statistica.')),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', help_text='Come questo punteggio si combina con altri.', max_length=3)),
            ],
            options={
                'verbose_name': 'Statistica',
                'verbose_name_plural': 'Statistiche',
            },
            bases=('personaggi.punteggio',),
        ),
        migrations.CreateModel(
            name='AbilitaStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=0)),
                ('abilita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.abilita')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'unique_together': {('abilita', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='abilita',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='abilita_statistiche', through='personaggi.AbilitaStatistica', to='personaggi.statistica', verbose_name='Statistiche modificate'),
        ),
    ]
