# Generated by Django 5.0.7 on 2025-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0013_statistica_abilitastatistica_abilita_statistiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilita_tier',
            name='costo_crediti',
            field=models.IntegerField(default=0, verbose_name="Costo dell'abilità in Crediti"),
        ),
        migrations.AlterField(
            model_name='abilita_tier',
            name='costo',
            field=models.IntegerField(default=0, verbose_name="Costo dell'abilità in Punti Caratteristica"),
        ),
    ]
