# Generated by Django 5.0.7 on 2025-11-06 14:14

import django.db.models.deletion
import django.utils.timezone
import personaggi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0016_statistica_parametro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='A_vista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('testo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Elemento dell'Oggetto",
                'verbose_name_plural': "Elementi dell'Oggetto",
            },
        ),
        migrations.CreateModel(
            name='Attivata',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
            ],
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventari',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
            ],
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
                ('aura', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oggetti_aura', to='personaggi.punteggio', verbose_name='Aura associata')),
            ],
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.CharField(default=personaggi.models.generate_short_id, editable=False, max_length=14, primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('testo', models.TextField(blank=True, null=True)),
                ('vista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.a_vista')),
            ],
        ),
        migrations.CreateModel(
            name='AttivataStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.attivata')),
            ],
            options={
                'verbose_name': 'Statistica (Valore Base)',
                'verbose_name_plural': 'Statistiche (Valori Base)',
                'unique_together': {('attivata', 'statistica')},
            },
        ),
        migrations.CreateModel(
            name='AttivataElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Elemento')),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.attivata')),
            ],
        ),
        migrations.AddField(
            model_name='attivata',
            name='elementi',
            field=models.ManyToManyField(blank=True, through='personaggi.AttivataElemento', to='personaggi.punteggio', verbose_name='Elementi associati'),
        ),
        migrations.AddField(
            model_name='attivata',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='attivata_statistiche_base', through='personaggi.AttivataStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
        migrations.CreateModel(
            name='Personaggio',
            fields=[
                ('inventario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.inventario')),
                ('data_nascita', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_morte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personaggio',
                'verbose_name_plural': 'Personaggi',
            },
            bases=('personaggi.inventario',),
        ),
        migrations.CreateModel(
            name='OggettoStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto')),
            ],
            options={
                'verbose_name': 'Statistica (Valore Base)',
                'verbose_name_plural': 'Statistiche (Valori Base)',
                'unique_together': {('oggetto', 'statistica')},
            },
        ),
        migrations.CreateModel(
            name='OggettoStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=0)),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto')),
            ],
            options={
                'unique_together': {('oggetto', 'statistica')},
            },
        ),
        migrations.CreateModel(
            name='OggettoInInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fine', models.DateTimeField(blank=True, help_text="Se Nullo, l'oggetto è attualmente in questo inventario.", null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracciamento_oggetti', to='personaggi.inventario')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracciamento_inventario', to='personaggi.oggetto')),
            ],
            options={
                'verbose_name': 'Tracciamento Oggetto in Inventario',
                'verbose_name_plural': 'Tracciamenti Oggetto in Inventario',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='OggettoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Elemento')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto')),
            ],
        ),
        migrations.AddField(
            model_name='oggetto',
            name='elementi',
            field=models.ManyToManyField(blank=True, through='personaggi.OggettoElemento', to='personaggi.punteggio', verbose_name='Elementi associati'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche', through='personaggi.OggettoStatistica', to='personaggi.statistica', verbose_name='Statistiche modificate'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche_base', through='personaggi.OggettoStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
        migrations.CreateModel(
            name='TransazioneSospesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('stato', models.CharField(choices=[('IN_ATTESA', 'In Attesa'), ('ACCETTATA', 'Accettata'), ('RIFIUTATA', 'Rifiutata')], default='IN_ATTESA', max_length=10)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_in_uscita_sospese', to='personaggi.inventario')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto')),
                ('richiedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_in_entrata_sospese', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Transazione Sospesa',
                'verbose_name_plural': 'Transazioni Sospese',
                'ordering': ['-data_richiesta'],
            },
        ),
        migrations.CreateModel(
            name='PersonaggioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('testo_log', models.TextField()),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_eventi', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Log Evento Personaggio',
                'verbose_name_plural': 'Log Eventi Personaggio',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PersonaggioAttivata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.attivata')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaggioAbilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('abilita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.abilita')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
            ],
        ),
        migrations.AddField(
            model_name='personaggio',
            name='abilita_possedute',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioAbilita', to='personaggi.abilita'),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='attivate_possedute',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioAttivata', to='personaggi.attivata'),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='proprietario',
            field=models.ForeignKey(blank=True, help_text="L'account utente che controlla questo personaggio.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaggi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreditoMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_credito', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Movimento Crediti',
                'verbose_name_plural': 'Movimenti Crediti',
                'ordering': ['-data'],
            },
        ),
    ]
