# Generated by Django 5.0.7 on 2025-11-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('personaggi', '0017_a_vista_attivata_inventario_manifesto_oggetto_qrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitastatistica',
            name='tipo_modificatore',
            field=models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='tipo_modificatore',
            field=models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3),
        ),
        migrations.CreateModel(
            name='AbilitaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('abilita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.abilita')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AttivataPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.attivata')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CaratteristicaModificatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificatore', models.DecimalField(decimal_places=2, default=1.0, help_text='Es: +1, +0.5, ecc. (valore additivo)', max_digits=5)),
                ('ogni_x_punti', models.IntegerField(default=1, help_text='Applica il modificatore ogni X punti di caratteristica.')),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, related_name='modificatori_dati', to='personaggi.punteggio')),
                ('statistica_modificata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificatori_ricevuti', to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Modificatore da Caratteristica',
                'verbose_name_plural': 'Modificatori da Caratteristiche',
                'unique_together': {('caratteristica', 'statistica_modificata')},
            },
        ),
        migrations.AddField(
            model_name='punteggio',
            name='modifica_statistiche',
            field=models.ManyToManyField(blank=True, related_name='modificata_da_caratteristiche', through='personaggi.CaratteristicaModificatore', to='personaggi.statistica'),
        ),
        migrations.CreateModel(
            name='OggettoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TierPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaggi_tier_plugin', to='personaggi.tier')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
