# Generated by Django 5.0.7 on 2025-11-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('personaggi', '0019_tipologiapersonaggio_punticaratteristicamovimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierpluginmodel',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_kor_tier_plugin', to='personaggi.tier'),
        ),
        migrations.CreateModel(
            name='TabellaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tabella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tabella')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
