# Generated by Django 5.0.7 on 2025-11-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0020_alter_tierpluginmodel_tier_tabellapluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggio',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personaggi', to='personaggi.tipologiapersonaggio'),
        ),
    ]
