# Generated by Django 5.0.7 on 2025-11-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0021_alter_personaggio_tipologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilita_tier',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='abilita_tier',
            name='costo_crediti',
        ),
        migrations.AddField(
            model_name='abilita',
            name='costo_crediti',
            field=models.IntegerField(default=0, verbose_name="Costo base dell'abilità in Crediti"),
        ),
        migrations.AddField(
            model_name='abilita',
            name='costo_pc',
            field=models.IntegerField(default=0, verbose_name="Costo base dell'abilità in Punti Caratteristica"),
        ),
    ]
