# Generated by Django 5.0.7 on 2025-11-13 16:22

import colorfield.fields
import django.db.models.deletion
import django_icon_picker.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0022_remove_abilita_tier_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punteggio',
            name='caratteristica',
        ),
        migrations.AddField(
            model_name='punteggio',
            name='caratteristica_relativa',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punteggi_caratteristica', to='personaggi.punteggio', verbose_name='Caratteristica relativa'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='colore',
            field=colorfield.fields.ColorField(default='#1976D2', help_text='Colore associato al punteggio (es. per icone).', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='icona',
            field=django_icon_picker.field.IconField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='caratteristica',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['CA', 'CO']}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Caratteristica'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='requisiti',
            field=models.ManyToManyField(help_text='Caratteristiche requisito di sblocco', related_name='abilita_req', through='personaggi.abilita_requisito', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione')], max_length=2, verbose_name='Tipo di punteggio'),
        ),
    ]
