# Generated by Django 5.0.7 on 2025-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0023_remove_punteggio_caratteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tiers/'),
        ),
    ]
