# Generated by Django 5.0.7 on 2025-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0025_punteggio_icona_old_alter_punteggio_icona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio',
            name='icona_old', # Il nome della colonna fantasma
            field=models.CharField(max_length=255, blank=True, null=True), # Rendila nullable
        ),
    ]
