# Generated by Django 5.0.7 on 2025-11-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0026_auto_20251114_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punteggio',
            name='icona_old',
        ),
        migrations.AddField(
            model_name='statistica',
            name='is_primaria',
            field=models.BooleanField(default=False, help_text='Seleziona se questa è una statistica primaria da mostrare in homepage.'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione'), ('CU', 'Culto'), ('VI', 'Via'), ('AR', 'Arte'), ('AR', 'Archetipo')], max_length=2, verbose_name='Tipo di punteggio'),
        ),
    ]
