# Generated by Django 5.0.7 on 2025-11-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0027_remove_punteggio_icona_old_statistica_is_primaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a_vista',
            options={'ordering': ['-data_creazione'], 'verbose_name': "Elemento dell'Oggetto", 'verbose_name_plural': "Elementi dell'Oggetto"},
        ),
    ]
