# Generated by Django 5.0.7 on 2025-11-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0028_alter_a_vista_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='mattoni',
        ),
        migrations.RemoveField(
            model_name='spell_mattone',
            name='mattone',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='aura',
        ),
        migrations.RemoveField(
            model_name='spell_mattone',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='spell_elemento',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='spell_elemento',
            name='elemento',
        ),
        migrations.CreateModel(
            name='Caratteristica',
            fields=[
            ],
            options={
                'verbose_name': 'Caratteristica (Gestione)',
                'verbose_name_plural': 'Caratteristiche (Gestione)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personaggi.punteggio',),
        ),
        migrations.DeleteModel(
            name='Mattone',
        ),
        migrations.DeleteModel(
            name='spell_mattone',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='spell_elemento',
        ),
    ]
