# Generated by Django 5.0.7 on 2025-11-18 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0028_alter_a_vista_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell_elemento',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='spell_mattone',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='spell_elemento',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='spell_mattone',
            name='mattone',
        ),
        migrations.CreateModel(
            name='Aura',
            fields=[
            ],
            options={
                'verbose_name': 'Aura (Gestione)',
                'verbose_name_plural': 'Aure (Gestione)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personaggi.punteggio',),
        ),
        migrations.CreateModel(
            name='Caratteristica',
            fields=[
            ],
            options={
                'verbose_name': 'Caratteristica (Gestione)',
                'verbose_name_plural': 'Caratteristiche (Gestione)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personaggi.punteggio',),
        ),
        migrations.AlterUniqueTogether(
            name='mattone',
            unique_together={('aura', 'caratteristica_associata')},
        ),
        migrations.AddField(
            model_name='mattone',
            name='caratteristica_associata',
            field=models.ForeignKey(default=2, limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, related_name='mattoni_caratteristica', to='personaggi.punteggio', verbose_name='Caratteristica associata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mattone',
            name='descrizione_mattone',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Mattone'),
        ),
        migrations.AddField(
            model_name='mattone',
            name='descrizione_metatalento',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Metatalento'),
        ),
        migrations.AddField(
            model_name='mattone',
            name='funzionamento_metatalento',
            field=models.CharField(choices=[('NE', 'Nessun Effetto'), ('VP', 'Valore per Punteggio'), ('TX', 'Solo Testo Addizionale'), ('LV', 'Solo abilità con livello pari o inferiore al punteggio')], default='NE', max_length=2, verbose_name='Funzionamento del Metatalento'),
        ),
        migrations.AddField(
            model_name='mattone',
            name='punteggio_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.punteggio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mattone',
            name='testo_addizionale',
            field=models.TextField(blank=True, help_text='Supporta parametri statistiche (es. {pv}) e il parametro {caratt}. Supporta moltiplicatori: {3*caratt}.', null=True, verbose_name='Testo Addizionale'),
        ),
        migrations.AlterField(
            model_name='attivataelemento',
            name='elemento',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['EL', 'MA']}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Elemento / Mattone'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='aura',
            field=models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='mattoni_aura', to='personaggi.punteggio', verbose_name='Aura associata'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione'), ('CU', 'Culto'), ('VI', 'Via'), ('AR', 'Arte'), ('AR', 'Archetipo'), ('MA', 'Mattone (Elemento)')], max_length=2, verbose_name='Tipo di punteggio'),
        ),
        migrations.CreateModel(
            name='MattoneStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=0)),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3)),
                ('mattone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'unique_together': {('mattone', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='mattone',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='mattoni_statistiche', through='personaggi.MattoneStatistica', to='personaggi.statistica', verbose_name='Statistiche modificate'),
        ),
        migrations.CreateModel(
            name='ModelloAura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('aura', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelli_definiti', to='personaggi.punteggio')),
                ('mattoni_proibiti', models.ManyToManyField(blank=True, related_name='proibiti_in_modelli', to='personaggi.mattone')),
            ],
            options={
                'verbose_name': 'Modello di Aura',
                'verbose_name_plural': 'Modelli di Aura',
            },
        ),
        migrations.CreateModel(
            name='PersonaggioModelloAura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello_aura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.modelloaura')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Personaggio - Modello Aura',
                'verbose_name_plural': 'Personaggio - Modelli Aura',
            },
        ),
        migrations.AddField(
            model_name='personaggio',
            name='modelli_aura',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioModelloAura', to='personaggi.modelloaura', verbose_name='Modelli di Aura'),
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='spell_elemento',
        ),
        migrations.DeleteModel(
            name='spell_mattone',
        ),
        migrations.RemoveField(
            model_name='mattone',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='mattone',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='mattone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mattone',
            name='nome',
        ),
    ]
