# Generated by Django 5.0.7 on 2025-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0030_aura_alter_attivataelemento_elemento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punteggio',
            options={'ordering': ['tipo', 'ordine', 'nome'], 'verbose_name': 'Punteggio', 'verbose_name_plural': 'Punteggi'},
        ),
        migrations.AddField(
            model_name='punteggio',
            name='ordine',
            field=models.IntegerField(default=0, help_text="Valore per l'ordinamento (più basso appare prima)"),
        ),
    ]
