# Generated by Django 5.0.7 on 2025-11-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0032_gruppo_messaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='is_mattone',
            field=models.BooleanField(default=False, verbose_name='è un mattone?'),
        ),
        migrations.AlterField(
            model_name='attivataelemento',
            name='elemento',
            field=models.ForeignKey(limit_choices_to={'is_mattone': True}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Elemento / Mattone'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione'), ('CU', 'Culto'), ('VI', 'Via'), ('AR', 'Arte'), ('AR', 'Archetipo')], max_length=2, verbose_name='Tipo di punteggio'),
        ),
    ]
