# Generated by Django 5.0.7 on 2025-11-21 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('personaggi', '0033_punteggio_is_mattone_alter_attivataelemento_elemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggettostatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Applica solo se Aura...'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Applica solo se Elemento...'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='is_generica',
            field=models.BooleanField(default=False, help_text='Se attivo, il valore è calcolato sul max delle altre aure.', verbose_name='Aura Generica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='is_soprannaturale',
            field=models.BooleanField(default=False, help_text='Se attivo è soprannaturale, altrimenti naturale.', verbose_name='Aura Soprannaturale'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='permette_infusioni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='permette_tessiture',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Infusione',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
                ('aura_infusione', models.ForeignKey(blank=True, limit_choices_to={'is_soprannaturale': True, 'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infusioni_secondarie', to='personaggi.punteggio', verbose_name='Aura di Infusione (Secondaria)')),
                ('aura_richiesta', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associate', to='personaggi.punteggio', verbose_name='Aura Requisito')),
            ],
            options={
                'verbose_name': 'Infusione',
                'verbose_name_plural': 'Infusioni',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='InfusioneMattone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('mattone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone')),
            ],
        ),
        migrations.AddField(
            model_name='infusione',
            name='mattoni',
            field=models.ManyToManyField(related_name='infusioni_utilizzatrici', through='personaggi.InfusioneMattone', to='personaggi.mattone', verbose_name='Mattoni Componenti'),
        ),
        migrations.CreateModel(
            name='InfusionePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='InfusioneStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('limit_a_aure', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Applica solo se Aura...')),
                ('limit_a_elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Applica solo se Elemento...')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='infusione',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='infusione_statistiche_base', through='personaggi.InfusioneStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
        migrations.CreateModel(
            name='PersonaggioInfusione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
            ],
        ),
        migrations.AddField(
            model_name='personaggio',
            name='infusioni_possedute',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioInfusione', to='personaggi.infusione'),
        ),
        migrations.CreateModel(
            name='Tessitura',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
                ('formula', models.TextField(blank=True, help_text='Parametri: {elem} (Elem. Principale), {rango} (Testo Rango). Usa anche statistiche pg.', null=True, verbose_name='Formula')),
                ('aura_richiesta', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associate', to='personaggi.punteggio', verbose_name='Aura Requisito')),
                ('elemento_principale', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'EL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.punteggio', verbose_name='Elemento Principale')),
            ],
            options={
                'verbose_name': 'Tessitura',
                'verbose_name_plural': 'Tessiture',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='PersonaggioTessitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tessitura')),
            ],
        ),
        migrations.AddField(
            model_name='personaggio',
            name='tessiture_possedute',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioTessitura', to='personaggi.tessitura'),
        ),
        migrations.CreateModel(
            name='TessituraMattone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('mattone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tessitura')),
            ],
        ),
        migrations.AddField(
            model_name='tessitura',
            name='mattoni',
            field=models.ManyToManyField(related_name='tessiture_utilizzatrici', through='personaggi.TessituraMattone', to='personaggi.mattone', verbose_name='Mattoni Componenti'),
        ),
        migrations.CreateModel(
            name='TessituraPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tessitura')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TessituraStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('limit_a_aure', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Applica solo se Aura...')),
                ('limit_a_elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Applica solo se Elemento...')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tessitura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tessitura',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='tessitura_statistiche_base', through='personaggi.TessituraStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
    ]
