# Generated by Django 5.0.7 on 2025-11-21 22:59

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0034_oggettostatistica_limit_a_aure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilita_prerequisito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_punteggio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_requisito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_sbloccata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_tier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attivatastatisticabase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='caratteristicamodificatore',
            options={'verbose_name': 'Modificatore da Caratteristica'},
        ),
        migrations.AlterModelOptions(
            name='creditomovimento',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='gruppo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messaggio',
            options={'ordering': ['-data_invio']},
        ),
        migrations.AlterModelOptions(
            name='oggettoininventario',
            options={'ordering': ['-data_inizio']},
        ),
        migrations.AlterModelOptions(
            name='oggettostatisticabase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personaggiolog',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='personaggiomodelloaura',
            options={'verbose_name_plural': 'Personaggio - Modelli Aura'},
        ),
        migrations.AlterModelOptions(
            name='punticaratteristicamovimento',
            options={'ordering': ['-data'], 'verbose_name': 'Movimento PC'},
        ),
        migrations.AlterModelOptions(
            name='tipologiapersonaggio',
            options={'verbose_name': 'Tipologia Personaggio'},
        ),
        migrations.AlterModelOptions(
            name='transazionesospesa',
            options={'ordering': ['-data_richiesta']},
        ),
        migrations.RemoveField(
            model_name='infusionestatisticabase',
            name='limit_a_aure',
        ),
        migrations.RemoveField(
            model_name='infusionestatisticabase',
            name='limit_a_elementi',
        ),
        migrations.RemoveField(
            model_name='tessiturastatisticabase',
            name='limit_a_aure',
        ),
        migrations.RemoveField(
            model_name='tessiturastatisticabase',
            name='limit_a_elementi',
        ),
        migrations.AddField(
            model_name='abilitastatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite'),
        ),
        migrations.AddField(
            model_name='abilitastatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti'),
        ),
        migrations.AddField(
            model_name='abilitastatistica',
            name='usa_limitazione_aura',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Aura'),
        ),
        migrations.AddField(
            model_name='abilitastatistica',
            name='usa_limitazione_elemento',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='usa_limitazione_aura',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Aura'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='usa_limitazione_elemento',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='caratteristica',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['CA', 'CO']}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='costo_crediti',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='costo_pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='nome',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='punteggio_acquisito',
            field=models.ManyToManyField(related_name='abilita_acquisizione', through='personaggi.abilita_punteggio', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='requisiti',
            field=models.ManyToManyField(related_name='abilita_req', through='personaggi.abilita_requisito', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='abilita_statistiche', through='personaggi.AbilitaStatistica', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='tabelle_sbloccate',
            field=models.ManyToManyField(related_name='abilita_sbloccante', through='personaggi.abilita_sbloccata', to='personaggi.tabella'),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='tiers',
            field=models.ManyToManyField(related_name='abilita', through='personaggi.abilita_tier', to='personaggi.tier'),
        ),
        migrations.AlterField(
            model_name='abilita_punteggio',
            name='valore',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='abilita_requisito',
            name='valore',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='abilita_tier',
            name='ordine',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attivata',
            name='elementi',
            field=models.ManyToManyField(blank=True, through='personaggi.AttivataElemento', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='attivata',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='attivata_statistiche_base', through='personaggi.AttivataStatisticaBase', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='attivataelemento',
            name='elemento',
            field=models.ForeignKey(limit_choices_to={'is_mattone': True}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='caratteristicamodificatore',
            name='modificatore',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='caratteristicamodificatore',
            name='ogni_x_punti',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='aura_infusione',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_soprannaturale': True, 'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infusioni_secondarie', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='aura_richiesta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associate', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='mattoni',
            field=models.ManyToManyField(related_name='infusioni_utilizzatrici', through='personaggi.InfusioneMattone', to='personaggi.mattone'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='infusione_statistiche_base', through='personaggi.InfusioneStatisticaBase', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='testo_addizionale',
            field=models.TextField(blank=True, null=True, verbose_name='Testo Addizionale'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='salva_in_cronologia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='tipo_messaggio',
            field=models.CharField(choices=[('BROAD', 'Broadcast'), ('GROUP', 'Gruppo'), ('INDV', 'Individuale')], default='BROAD', max_length=5),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='aura',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oggetti_aura', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='elementi',
            field=models.ManyToManyField(blank=True, through='personaggi.OggettoElemento', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche', through='personaggi.OggettoStatistica', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche_base', through='personaggi.OggettoStatisticaBase', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='oggettoelemento',
            name='elemento',
            field=models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='oggettoininventario',
            name='data_fine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oggettostatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite'),
        ),
        migrations.AlterField(
            model_name='oggettostatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti'),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaggi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='colore',
            field=colorfield.fields.ColorField(default='#1976D2', help_text='Colore associato al punteggio.', image_field=None, max_length=25, samples=None, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='is_generica',
            field=models.BooleanField(default=False, verbose_name='Aura Generica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='is_soprannaturale',
            field=models.BooleanField(default=False, verbose_name='Aura Soprannaturale'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='ordine',
            field=models.IntegerField(default=0, help_text="Valore per l'ordinamento"),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='is_primaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='parametro',
            field=models.CharField(blank=True, help_text="Es. 'pv'", max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='tipo_modificatore',
            field=models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='valore_base_predefinito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='valore_predefinito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='aura_richiesta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associate', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='elemento_principale',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'EL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, help_text='Parametri: {elem}, {rango}.', null=True, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='mattoni',
            field=models.ManyToManyField(related_name='tessiture_utilizzatrici', through='personaggi.TessituraMattone', to='personaggi.mattone'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='tessitura_statistiche_base', through='personaggi.TessituraStatisticaBase', to='personaggi.statistica'),
        ),
        migrations.CreateModel(
            name='InfusioneStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_limitazione_aura', models.BooleanField(default=False, verbose_name='Usa Limitazione Aura')),
                ('usa_limitazione_elemento', models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento')),
                ('valore', models.IntegerField(default=0)),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('limit_a_aure', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite')),
                ('limit_a_elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'unique_together': {('infusione', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='infusione',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='infusione_statistiche', through='personaggi.InfusioneStatistica', to='personaggi.statistica'),
        ),
        migrations.CreateModel(
            name='TessituraStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_limitazione_aura', models.BooleanField(default=False, verbose_name='Usa Limitazione Aura')),
                ('usa_limitazione_elemento', models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento')),
                ('valore', models.IntegerField(default=0)),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3)),
                ('limit_a_aure', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite')),
                ('limit_a_elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.tessitura')),
            ],
            options={
                'unique_together': {('tessitura', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='tessitura',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='tessitura_statistiche', through='personaggi.TessituraStatistica', to='personaggi.statistica'),
        ),
    ]
