# Generated by Django 5.0.7 on 2025-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0036_remove_infusione_statistiche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattone',
            name='funzionamento_metatalento',
            field=models.CharField(choices=[('NE', 'Nessun Effetto'), ('VP', 'Valore per Punteggio'), ('TX', 'Solo Testo Addizionale'), ('LV', 'Solo abilità con livello pari o inferiore al punteggio')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='tabella',
            name='nome',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Formula'),
        ),
    ]
