# Generated by Django 5.0.7 on 2025-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0037_alter_mattone_funzionamento_metatalento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mattone',
            name='dichiarazione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
