# Generated by Django 5.0.7 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0038_mattone_dichiarazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattone',
            name='dichiarazione',
            field=models.CharField(blank=True, help_text='Testo che sostituisce {elem} se questo mattone è un Elemento.', max_length=30, null=True, verbose_name='Dichiarazione (per Elementi)'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='funzionamento_metatalento',
            field=models.CharField(choices=[('NE', 'Nessun Effetto'), ('VP', 'Valore per Punteggio'), ('TX', 'Solo Testo Addizionale'), ('LV', 'Solo abilità con livello pari o inferiore')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, help_text='Parametri: {elem}, {rango}.', null=True, verbose_name='Formula'),
        ),
    ]
