# Generated by Django 5.0.7 on 2025-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0039_alter_mattone_dichiarazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitastatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Espressione logica. Variabili: {caratt}, {livello}, {pv}, ecc.', max_length=255, null=True, verbose_name='Condizione (es. caratt>6)'),
        ),
        migrations.AddField(
            model_name='abilitastatistica',
            name='usa_condizione_text',
            field=models.BooleanField(default=False, verbose_name='Usa Condizione Testuale'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Espressione logica. Variabili: {caratt}, {livello}, {pv}, ecc.', max_length=255, null=True, verbose_name='Condizione (es. caratt>6)'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='usa_condizione_text',
            field=models.BooleanField(default=False, verbose_name='Usa Condizione Testuale'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Espressione logica. Variabili: {caratt}, {livello}, {pv}, ecc.', max_length=255, null=True, verbose_name='Condizione (es. caratt>6)'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='usa_condizione_text',
            field=models.BooleanField(default=False, verbose_name='Usa Condizione Testuale'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='dichiarazione',
            field=models.TextField(blank=True, help_text='Testo per {elem}.', null=True, verbose_name='Dichiarazione'),
        ),
    ]
