# Generated by Django 5.0.7 on 2025-11-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0043_oggetto_costo_crediti'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelloaura',
            name='usa_condizione_mattone',
            field=models.BooleanField(default=False, help_text='Se attivo, le formule dei mattoni appaiono solo se i requisiti sotto sono soddisfatti.', verbose_name='Richiede Condizione per F. Mattone'),
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='usa_formula_per_mattone',
            field=models.BooleanField(default=False, verbose_name='Abilita Formula per Mattone'),
        ),
        migrations.CreateModel(
            name='ModelloAuraRequisitoMattone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_mattone_rel', to='personaggi.modelloaura')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
            ],
            options={
                'verbose_name': 'Requisito Formula x Mattone',
                'verbose_name_plural': 'Requisiti Formula x Mattone',
            },
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='requisiti_mattone',
            field=models.ManyToManyField(blank=True, related_name='modelli_req_mattone', through='personaggi.ModelloAuraRequisitoMattone', to='personaggi.punteggio'),
        ),
    ]
