# Generated by Django 5.0.7 on 2025-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0050_alter_abilita_prerequisito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='aure_infusione_consentite',
            field=models.ManyToManyField(blank=True, help_text="Seleziona quali aure possono essere usate come fonte di mattoni quando questa aura è selezionata come 'Aura Richiesta'.", related_name='puo_essere_infusa_in', to='personaggi.punteggio'),
        ),
    ]
