# Generated by Django 5.0.7 on 2025-11-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0051_punteggio_aure_infusione_consentite'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='costo_ricarica_crediti',
            field=models.IntegerField(default=0, help_text='Costo per ricaricare una singola carica (default 0).', verbose_name='Costo Ricarica (Crediti)'),
        ),
        migrations.AddField(
            model_name='infusione',
            name='durata_attivazione',
            field=models.IntegerField(default=0, help_text="Se > 0, attiva un timer nel frontend all'uso della carica.", verbose_name='Durata Attivazione (secondi)'),
        ),
        migrations.AddField(
            model_name='infusione',
            name='metodo_ricarica',
            field=models.TextField(blank=True, help_text="Descrizione parametrizzata (es. 'Spendi {costo} crediti'). Obbligatorio per Tech.", null=True, verbose_name='Metodo di Ricarica'),
        ),
        migrations.AddField(
            model_name='infusione',
            name='statistica_cariche',
            field=models.ForeignKey(blank=True, help_text="Se vuoto, l'oggetto non ha cariche.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infusioni_cariche', to='personaggi.statistica', verbose_name='Statistica per Cariche Max'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. 2d6, o vuoto se non arma', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='cariche_attuali',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='costo_acquisto',
            field=models.IntegerField(default=0, verbose_name='Costo in Negozio (Crediti)'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='in_vendita',
            field=models.BooleanField(default=False, help_text='Visibile nel Negozio Generale?'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='infusione_generatrice',
            field=models.ForeignKey(blank=True, help_text="L'infusione da cui deriva questa Materia/Mod/Innesto", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oggetti_generati', to='personaggi.infusione'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='is_tecnologico',
            field=models.BooleanField(default=False, verbose_name='Oggetto Tecnologico'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='ospitato_su',
            field=models.ForeignKey(blank=True, help_text='Se impostato, questo potenziamento è montato su questo oggetto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potenziamenti_installati', to='personaggi.oggetto'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='slot_corpo',
            field=models.CharField(blank=True, choices=[('HD', 'Testa'), ('TR', 'Tronco'), ('RA', 'Braccio Dx'), ('LA', 'Braccio Sx'), ('RL', 'Gamba Dx'), ('LL', 'Gamba Sx')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='tipo_oggetto',
            field=models.CharField(choices=[('FIS', 'Oggetto Fisico'), ('MAT', 'Materia (Mondana)'), ('MOD', 'Mod (Tecnologica)'), ('INN', 'Innesto (Tecnologico)'), ('MUT', 'Mutazione (Innata)')], default='FIS', max_length=3),
        ),
        migrations.CreateModel(
            name='ClasseOggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('max_mod_totali', models.IntegerField(default=0, help_text='Numero massimo assoluto di Mod installabili (indipendentemente dal tipo).', verbose_name='Max Mod Totali')),
                ('mattoni_materia_permessi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'CA'}, related_name='classi_oggetti_materia_permessa', to='personaggi.punteggio')),
            ],
        ),
        migrations.AddField(
            model_name='oggetto',
            name='classe_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.classeoggetto', verbose_name='Classe (Slot)'),
        ),
        migrations.CreateModel(
            name='ClasseOggettoLimiteMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_installabili', models.IntegerField(default=1, help_text='Quante mod che contengono mattoni di questa caratteristica possono essere montate.', verbose_name='Max Mod di questo tipo')),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('classe_oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.classeoggetto')),
            ],
            options={
                'verbose_name': 'Limite Mod per Caratteristica',
                'verbose_name_plural': 'Limiti Mod per Caratteristica',
                'unique_together': {('classe_oggetto', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='classeoggetto',
            name='limitazioni_mod',
            field=models.ManyToManyField(related_name='classi_oggetti_regole_mod', through='personaggi.ClasseOggettoLimiteMod', to='personaggi.punteggio', verbose_name='Limiti Mod per Caratteristica'),
        ),
    ]
