# Generated by Django 5.0.7 on 2025-11-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0052_infusione_costo_ricarica_crediti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classeoggetto',
            options={'verbose_name': 'Classe Oggetto (Regole)', 'verbose_name_plural': 'Classi Oggetto (Regole)'},
        ),
        migrations.AlterModelOptions(
            name='classeoggettolimitemod',
            options={'verbose_name': 'Limite Mod per Caratteristica'},
        ),
        migrations.RemoveField(
            model_name='oggetto',
            name='costo_crediti',
        ),
        migrations.AlterField(
            model_name='classeoggetto',
            name='mattoni_materia_permessi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'CA'}, related_name='classi_oggetti_materia_permessa', to='personaggi.punteggio', verbose_name='Caratt. Materia Permesse'),
        ),
        migrations.AlterField(
            model_name='classeoggetto',
            name='max_mod_totali',
            field=models.IntegerField(default=0, help_text='Numero massimo assoluto di Mod installabili.', verbose_name='Max Mod Totali'),
        ),
        migrations.AlterField(
            model_name='classeoggettolimitemod',
            name='max_installabili',
            field=models.IntegerField(default=1, help_text='Quante mod con mattoni di questa caratteristica possono essere montate.', verbose_name='Max Mod di questo tipo'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. 2d6', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='classe_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.classeoggetto', verbose_name='Classe (Slot/Regole)'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='costo_acquisto',
            field=models.IntegerField(default=0, verbose_name='Costo (Crediti)'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='in_vendita',
            field=models.BooleanField(default=False, verbose_name='In vendita al negozio?'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='is_tecnologico',
            field=models.BooleanField(default=False, verbose_name='È Tecnologico?'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='ospitato_su',
            field=models.ForeignKey(blank=True, help_text="L'oggetto su cui questo potenziamento è montato.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potenziamenti_installati', to='personaggi.oggetto'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='slot_corpo',
            field=models.CharField(blank=True, choices=[('HD', 'Testa'), ('TR', 'Tronco'), ('RA', 'Braccio Dx'), ('LA', 'Braccio Sx'), ('RL', 'Gamba Dx'), ('LL', 'Gamba Sx')], help_text='Solo per Innesti e Mutazioni', max_length=2, null=True),
        ),
    ]
