# Generated by Django 5.0.7 on 2025-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0053_alter_classeoggetto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='is_equipaggiato',
            field=models.BooleanField(default=False, help_text="Se True, l'oggetto sta fornendo i suoi bonus e occupa Capacità Oggetti.", verbose_name='Equipaggiato?'),
        ),
    ]
