# Generated by Django 5.0.7 on 2025-12-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0054_oggetto_is_equipaggiato'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_acquisto_infusione',
            field=models.ForeignKey(blank=True, help_text="Statistica che definisce il costo per mattone per acquistare (apprendere) un'infusione.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_inf', to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_acquisto_tessitura',
            field=models.ForeignKey(blank=True, help_text='Statistica che definisce il costo per mattone per acquistare una tessitura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_tes', to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_infusione',
            field=models.ForeignKey(blank=True, help_text="Statistica che definisce il costo (crediti) per mattone per creare un'infusione.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_inf', to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_tessitura',
            field=models.ForeignKey(blank=True, help_text='Statistica che definisce il costo per mattone per creare una tessitura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_tes', to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_forgiatura',
            field=models.ForeignKey(blank=True, help_text="Statistica che definisce il costo (crediti) per mattone per forgiare l'oggetto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_forgia', to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_tempo_forgiatura',
            field=models.ForeignKey(blank=True, help_text="Statistica che definisce il tempo (secondi) per mattone per forgiare l'oggetto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_tempo_forgia', to='personaggi.statistica'),
        ),
        migrations.CreateModel(
            name='ForgiaturaInCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine_prevista', models.DateTimeField()),
                ('slot_target', models.CharField(blank=True, max_length=2, null=True)),
                ('completata', models.BooleanField(default=False)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgiature_attive', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Forgiatura in Corso',
                'verbose_name_plural': 'Forgiature in Corso',
                'ordering': ['data_fine_prevista'],
            },
        ),
    ]
