# Generated by Django 5.0.7 on 2025-12-03 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0057_remove_infusione_mattoni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tessituramattone',
            name='mattone',
        ),
        migrations.RemoveField(
            model_name='tessituramattone',
            name='tessitura',
        ),
        migrations.AlterModelOptions(
            name='propostatecnicamattone',
            options={},
        ),
        migrations.AlterField(
            model_name='classeoggetto',
            name='max_mod_totali',
            field=models.IntegerField(default=0, verbose_name='Max Mod Totali'),
        ),
        migrations.AlterField(
            model_name='classeoggettolimitemod',
            name='max_installabili',
            field=models.IntegerField(default=1, verbose_name='Max Mod di questo tipo'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='costo_ricarica_crediti',
            field=models.IntegerField(default=0, verbose_name='Costo Ricarica (Crediti)'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='durata_attivazione',
            field=models.IntegerField(default=0, verbose_name='Durata Attivazione (secondi)'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, help_text="Es. {forza} + {livello} o 2d6 + {mira}. Se l'oggetto è un'arma, questo valore sovrascrive l'attacco base.", max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='metodo_ricarica',
            field=models.TextField(blank=True, null=True, verbose_name='Metodo di Ricarica'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='statistica_cariche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infusioni_cariche', to='personaggi.statistica', verbose_name='Statistica per Cariche Max'),
        ),
        migrations.AlterField(
            model_name='modelloaura',
            name='mattoni_obbligatori',
            field=models.ManyToManyField(blank=True, related_name='obbligatori_in_modelli', to='personaggi.mattone', verbose_name='Mattoni Obbligatori'),
        ),
        migrations.AlterField(
            model_name='modelloaura',
            name='usa_condizione_caratt',
            field=models.BooleanField(default=False, verbose_name='Richiede Condizione per F. Caratt.'),
        ),
        migrations.AlterField(
            model_name='modelloaura',
            name='usa_condizione_doppia',
            field=models.BooleanField(default=False, verbose_name='Richiede Condizione per Doppia'),
        ),
        migrations.AlterField(
            model_name='modelloaura',
            name='usa_condizione_mattone',
            field=models.BooleanField(default=False, verbose_name='Richiede Condizione per F. Mattone'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='is_equipaggiato',
            field=models.BooleanField(default=False, verbose_name='Equipaggiato?'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='aure_infusione_consentite',
            field=models.ManyToManyField(blank=True, related_name='puo_essere_infusa_in', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_acquisto_infusione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_inf', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_acquisto_tessitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_tes', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_infusione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_inf', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_tessitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_tes', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_forgiatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_forgia', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_tempo_forgiatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_tempo_forgia', to='personaggi.statistica'),
        ),
        migrations.DeleteModel(
            name='InfusioneMattone',
        ),
        migrations.DeleteModel(
            name='TessituraMattone',
        ),
    ]
