# Generated by Django 5.0.7 on 2025-12-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0060_punteggio_stat_costo_invio_proposta_infusione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaAssemblaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerta_crediti', models.IntegerField(default=0, verbose_name='Offerta pagamento')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('PEND', 'In Attesa'), ('COMP', 'Completata'), ('RIFI', 'Rifiutata')], default='PEND', max_length=4)),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_assemblaggio_ricevute', to='personaggi.personaggio')),
                ('committente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_assemblaggio_inviate', to='personaggi.personaggio')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_componente', to='personaggi.oggetto')),
                ('oggetto_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_host', to='personaggi.oggetto')),
            ],
            options={
                'verbose_name': 'Richiesta Assemblaggio',
                'verbose_name_plural': 'Richieste Assemblaggio',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
