# Generated by Django 5.0.7 on 2025-12-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0061_richiestaassemblaggio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oggetto',
            name='elementi',
        ),
        migrations.CreateModel(
            name='OggettoCaratteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='personaggi.oggetto')),
            ],
            options={
                'verbose_name': 'Caratteristica Oggetto',
                'verbose_name_plural': 'Caratteristiche Oggetto',
                'unique_together': {('oggetto', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='oggetto',
            name='caratteristiche',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'CA'}, related_name='oggetti_utilizzatori', through='personaggi.OggettoCaratteristica', to='personaggi.punteggio'),
        ),
        migrations.DeleteModel(
            name='OggettoElemento',
        ),
    ]
