# Generated by Django 5.0.7 on 2025-12-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0063_alter_richiestaassemblaggio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestaassemblaggio',
            name='infusione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='richieste_forgiatura', to='personaggi.infusione'),
        ),
        migrations.AlterField(
            model_name='richiestaassemblaggio',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='richieste_componente', to='personaggi.oggetto'),
        ),
        migrations.AlterField(
            model_name='richiestaassemblaggio',
            name='oggetto_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='richieste_host', to='personaggi.oggetto'),
        ),
        migrations.AlterField(
            model_name='richiestaassemblaggio',
            name='tipo_operazione',
            field=models.CharField(choices=[('INST', 'Installazione'), ('RIMO', 'Rimozione'), ('FORG', 'Forgiatura')], default='INST', max_length=4, verbose_name='Tipo Operazione'),
        ),
    ]
