# Generated by Django 5.0.7 on 2025-12-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0065_forgiaturaincorso_destinatario_finale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgiaturaincorso',
            name='destinatario_finale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forgiature_in_arrivo', to='personaggi.personaggio', verbose_name='Destinatario Finale (se conto terzi)'),
        ),
    ]
