# Generated by Django 5.0.7 on 2025-12-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0066_alter_forgiaturaincorso_destinatario_finale'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='slot_corpo_permessi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Slot Corpo Consentiti'),
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='slot_corpo_permessi',
            field=models.CharField(blank=True, help_text='Lista slot separati da virgola (es. HD1,TR1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_innesti',
            field=models.BooleanField(default=False, verbose_name='Produce INNESTI (Corpo)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_materia',
            field=models.BooleanField(default=False, verbose_name='Produce MATERIA (Oggetti)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_mod',
            field=models.BooleanField(default=False, verbose_name='Produce MOD (Oggetti)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_mutazioni',
            field=models.BooleanField(default=False, verbose_name='Produce MUTAZIONI (Corpo)'),
        ),
        migrations.AddField(
            model_name='richiestaassemblaggio',
            name='forgiatura_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_installazione', to='personaggi.forgiaturaincorso'),
        ),
        migrations.AddField(
            model_name='richiestaassemblaggio',
            name='slot_destinazione',
            field=models.CharField(blank=True, choices=[('HD1', 'Testa 1'), ('HD2', 'Testa 2'), ('TR1', 'Tronco 1'), ('TR2', 'Tronco 2'), ('RA', 'Braccio Dx'), ('LA', 'Braccio Sx'), ('RL', 'Gamba Dx'), ('LL', 'Gamba Sx')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='slot_corpo',
            field=models.CharField(blank=True, choices=[('HD1', 'Testa 1'), ('HD2', 'Testa 2'), ('TR1', 'Tronco 1'), ('TR2', 'Tronco 2'), ('RA', 'Braccio Dx'), ('LA', 'Braccio Sx'), ('RL', 'Gamba Dx'), ('LL', 'Gamba Sx')], help_text='Solo per Innesti e Mutazioni', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='richiestaassemblaggio',
            name='tipo_operazione',
            field=models.CharField(choices=[('INST', 'Installazione Mod/Materia'), ('RIMO', 'Rimozione'), ('FORG', 'Forgiatura Conto Terzi'), ('GRAF', 'Operazione Chirurgica (Innesto/Mutazione)')], default='INST', max_length=4, verbose_name='Tipo Operazione'),
        ),
    ]
