# Generated by Django 5.0.7 on 2025-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0069_alter_forgiaturaincorso_data_inizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='potenziamenti_multi_slot',
            field=models.BooleanField(default=False, verbose_name='Multi-Slot? (Più copie sullo stesso oggetto)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_aumenti',
            field=models.BooleanField(default=False, verbose_name='Produce Aumenti (Innesti/Mutazioni)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='produce_potenziamenti',
            field=models.BooleanField(default=False, verbose_name='Produce Potenziamenti (Mod/Materia)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='spegne_a_zero_cariche',
            field=models.BooleanField(default=False, verbose_name='Si spegne a 0 cariche? (Tecnologico)'),
        ),
    ]
