# Generated by Django 5.0.7 on 2025-12-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0070_punteggio_potenziamenti_multi_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punteggio',
            name='produce_innesti',
        ),
        migrations.RemoveField(
            model_name='punteggio',
            name='produce_materia',
        ),
        migrations.RemoveField(
            model_name='punteggio',
            name='produce_mod',
        ),
        migrations.RemoveField(
            model_name='punteggio',
            name='produce_mutazioni',
        ),
    ]
