# Generated by Django 5.0.7 on 2025-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0071_remove_punteggio_produce_innesti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='nome_tipo_aumento',
            field=models.CharField(blank=True, help_text='Es. Innesto, Mutazione', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='nome_tipo_potenziamento',
            field=models.CharField(blank=True, help_text='Es. Mod, Materia', max_length=50, null=True),
        ),
    ]
