# Generated by Django 5.0.7 on 2025-12-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0073_punteggio_nome_tessitura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punteggio',
            old_name='nome_tessitura',
            new_name='nome_tipo_tessitura',
        ),
    ]
