# Generated by Django 5.0.7 on 2025-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0074_rename_nome_tessitura_punteggio_nome_tipo_tessitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio',
            name='nome_tipo_tessitura',
            field=models.CharField(blank=True, help_text='Es. Incantesimo, Preghiera...', max_length=50, null=True),
        ),
    ]
