# Generated by Django 5.0.7 on 2025-12-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0075_alter_punteggio_nome_tipo_tessitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='data_fine_attivazione',
            field=models.DateTimeField(blank=True, help_text="Se impostato, l'oggetto è attivo fino a questa data.", null=True),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='statistiche_temporanee',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valori Correnti Statistiche'),
        ),
    ]
