# Generated by Django 5.0.7 on 2025-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0076_oggetto_data_fine_attivazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgiaturaincorso',
            name='slot_target',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
