# Generated by Django 5.0.7 on 2025-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0077_alter_forgiaturaincorso_slot_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='tipo_risultato',
            field=models.CharField(choices=[('POT', 'Potenziamento (Mod/Materia)'), ('INN', 'Aumento Corporeo (Innesto/Mutazione)')], default='POT', max_length=3, verbose_name='Tipo Oggetto Finale'),
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='tipo_risultato_atteso',
            field=models.CharField(choices=[('POT', 'Potenziamento (Mod/Materia)'), ('INN', 'Aumento Corporeo (Innesto/Mutazione)')], default='POT', max_length=3, verbose_name='Tipo Oggetto Finale'),
        ),
    ]
