# Generated by Django 5.0.7 on 2025-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0078_infusione_tipo_risultato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='is_pesante',
            field=models.BooleanField(default=False, help_text='Se attivo, questo oggetto conta per il limite OGP (Oggetti Pesanti).', verbose_name='È un oggetto Pesante?'),
        ),
        migrations.AddField(
            model_name='oggettobase',
            name='is_pesante',
            field=models.BooleanField(default=False, help_text='Se attivo, questo oggetto conta per il limite OGP (Oggetti Pesanti).', verbose_name='È un oggetto Pesante?'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='tipo_risultato',
            field=models.CharField(choices=[('POT', 'Potenziamento (Mod/Materia)'), ('AUM', 'Aumento Corporeo (Innesto/Mutazione)')], default='POT', max_length=3, verbose_name='Tipo Oggetto Finale'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='tipo_oggetto',
            field=models.CharField(choices=[('FIS', 'Oggetto Fisico'), ('MAT', 'Materia (Mondana)'), ('MOD', 'Mod (Tecnologica)'), ('INN', 'Innesto (Tecnologico)'), ('MUT', 'Mutazione (Innata)'), ('AUM', 'Aumento (installazione corporea)'), ('POT', 'Potenziamento (installazione su oggetti)')], default='FIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='tipo_oggetto',
            field=models.CharField(choices=[('FIS', 'Oggetto Fisico'), ('MAT', 'Materia (Mondana)'), ('MOD', 'Mod (Tecnologica)'), ('INN', 'Innesto (Tecnologico)'), ('MUT', 'Mutazione (Innata)'), ('AUM', 'Aumento (installazione corporea)'), ('POT', 'Potenziamento (installazione su oggetti)')], default='FIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='propostatecnica',
            name='tipo_risultato_atteso',
            field=models.CharField(choices=[('POT', 'Potenziamento (Mod/Materia)'), ('AUM', 'Aumento Corporeo (Innesto/Mutazione)')], default='POT', max_length=3, verbose_name='Tipo Oggetto Finale'),
        ),
    ]
