# Generated by Django 5.0.7 on 2025-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0079_oggetto_is_pesante_oggettobase_is_pesante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='is_pesante',
            field=models.BooleanField(default=False, help_text="Se attivo, L'oggetto generato conta per il limite OGP (Oggetti Pesanti).", verbose_name='Genera un oggetto Pesante?'),
        ),
    ]
