# Generated by Django 5.0.7 on 2025-12-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0080_infusione_is_pesante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. 2d6', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. 2d6', max_length=200, null=True),
        ),
    ]
