# Generated by Django 5.0.7 on 2025-12-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0082_abilita_aura_riferimento_abilita_is_tratto_aura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazionelivelloaura',
            name='livello',
            field=models.IntegerField(blank=True, default=1, help_text='A che valore di aura si sblocca questa scelta?', null=True),
        ),
    ]
