# Generated by Django 5.0.7 on 2025-12-20 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('personaggi', '0083_alter_configurazionelivelloaura_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostatecnica',
            name='effetto',
            field=models.TextField(blank=True, null=True, verbose_name='Effetto (Cerimoniale)'),
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='prerequisiti',
            field=models.TextField(blank=True, null=True, verbose_name='Prerequisiti (Cerimoniale)'),
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='svolgimento',
            field=models.TextField(blank=True, null=True, verbose_name='Svolgimento (Cerimoniale)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='permette_cerimoniali',
            field=models.BooleanField(default=False, verbose_name='Permette Cerimoniali'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_acquisto_cerimoniale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_cer', to='personaggi.statistica', verbose_name='Stat. Costo Acquisto Cerimoniale'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_cerimoniale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_cer', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Cerimoniale'),
        ),
        migrations.AlterField(
            model_name='propostatecnica',
            name='tipo',
            field=models.CharField(choices=[('INF', 'Infusione'), ('TES', 'Tessitura'), ('CER', 'Cerimoniale')], max_length=3),
        ),
        migrations.CreateModel(
            name='Cerimoniale',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
                ('prerequisiti', models.TextField(blank=True, null=True, verbose_name='Prerequisiti')),
                ('svolgimento', models.TextField(blank=True, null=True, verbose_name='Svolgimento')),
                ('effetto', models.TextField(blank=True, null=True, verbose_name='Effetto')),
                ('aura_richiesta', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associate', to='personaggi.punteggio')),
                ('proposta_creazione', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cerimoniale_generato', to='personaggi.propostatecnica', verbose_name='Proposta Originale')),
            ],
            options={
                'verbose_name': 'Cerimoniale',
                'verbose_name_plural': 'Cerimoniali',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='CerimonialeCaratteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('cerimoniale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='personaggi.cerimoniale')),
            ],
            options={
                'unique_together': {('cerimoniale', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='cerimoniale',
            name='caratteristiche',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'CA'}, related_name='cerimoniali_utilizzatori', through='personaggi.CerimonialeCaratteristica', to='personaggi.punteggio'),
        ),
        migrations.CreateModel(
            name='CerimonialePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('cerimoniale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.cerimoniale')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PersonaggioCerimoniale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisizione', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerimoniale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.cerimoniale')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
            ],
        ),
        migrations.AddField(
            model_name='personaggio',
            name='cerimoniali_posseduti',
            field=models.ManyToManyField(blank=True, through='personaggi.PersonaggioCerimoniale', to='personaggi.cerimoniale'),
        ),
    ]
