# Generated by Django 5.0.7 on 2025-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0085_personaggio_impostazioni_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerimoniale',
            name='liv',
            field=models.IntegerField(default=1, verbose_name='Livello'),
        ),
    ]
