# Generated by Django 5.0.7 on 2026-01-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0086_cerimoniale_liv'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('alert_suono', models.BooleanField(default=False, help_text='Riproduce un suono alla scadenza su tutti i client', verbose_name='Alert Sonoro')),
                ('notifica_push', models.BooleanField(default=False, help_text='Invia una notifica di sistema al termine del countdown', verbose_name='Notifica App')),
                ('messaggio_in_app', models.BooleanField(default=True, help_text='Mostra un messaggio in-app quando il timer scade', verbose_name='Messaggio Scadenza')),
            ],
            options={
                'verbose_name': 'Tipologia Timer',
                'verbose_name_plural': 'Tipologie Timer',
            },
        ),
        migrations.CreateModel(
            name='TimerQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata_secondi', models.PositiveIntegerField(default=60, verbose_name='Durata Countdown (secondi)')),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurazione_timer', to='personaggi.qrcode')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_collegati', to='personaggi.tipologiatimer')),
            ],
            options={
                'verbose_name': 'Configurazione Timer QR',
                'verbose_name_plural': 'Configurazioni Timer QR',
            },
        ),
        migrations.CreateModel(
            name='StatoTimerAttivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fine', models.DateTimeField(verbose_name='Data e Ora Scadenza')),
                ('tipologia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stato_corrente', to='personaggi.tipologiatimer')),
            ],
            options={
                'verbose_name': 'Stato Timer Attivo',
                'verbose_name_plural': 'Stati Timer Attivi',
            },
        ),
    ]
