# Generated by Django 5.0.7 on 2026-01-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0088_timerqrcode_ultima_attivazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostatecnica',
            name='livello_proposto',
            field=models.IntegerField(default=1, verbose_name='Livello Scelto'),
        ),
        migrations.AlterField(
            model_name='propostatecnica',
            name='tipo_risultato_atteso',
            field=models.CharField(blank=True, choices=[('POT', 'Potenziamento (Mod/Materia)'), ('AUM', 'Aumento Corporeo (Innesto/Mutazione)')], default='POT', max_length=3, null=True, verbose_name='Tipo Oggetto Finale'),
        ),
    ]
