# Generated by Django 5.0.7 on 2026-01-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0090_punteggio_stat_costo_invio_proposta_cerimoniale'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='costume',
            field=models.TextField(blank=True, null=True, verbose_name='Appunti Costume'),
        ),
    ]
