# Generated by Django 5.0.7 on 2026-01-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0091_personaggio_costume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilita_requisito',
            name='requisito',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ('CA', 'CO', 'ST', 'AU')}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
    ]
