# Generated by Django 5.0.7 on 2026-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0092_alter_abilita_requisito_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='tipo',
            field=models.CharField(choices=[('G0', 'Tabelle Generali'), ('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3'), ('T4', 'Tier 4')], max_length=2),
        ),
    ]
