# Generated by Django 5.0.7 on 2026-01-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0094_dichiarazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dichiarazione',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Dichiarazione / Glossario', 'verbose_name_plural': 'Dichiarazioni e Glossario'},
        ),
        migrations.RemoveField(
            model_name='dichiarazione',
            name='testo',
        ),
        migrations.AddField(
            model_name='dichiarazione',
            name='descrizione',
            field=models.TextField(default='', verbose_name='Descrizione della dichiarazione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dichiarazione',
            name='dichiarazione',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Dichiarazione / Termine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dichiarazione',
            name='nome',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Nome Dichiarazione'),
            preserve_default=False,
        ),
    ]
