# Generated by Django 5.0.7 on 2026-01-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0096_messaggio_is_staff_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggio',
            name='tipo_messaggio',
            field=models.CharField(choices=[('BROAD', 'Broadcast'), ('GROUP', 'Gruppo'), ('INDV', 'Individuale'), ('STAFF', 'Staff')], default='BROAD', max_length=5),
        ),
    ]
