# Generated by Django 5.0.7 on 2026-01-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0097_alter_messaggio_tipo_messaggio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaggioStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaggiostatisticabase_set', to='personaggi.personaggio')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaggi_che_hanno_base', to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Statistica Base Personaggio',
                'verbose_name_plural': 'Statistiche Base Personaggio',
                'unique_together': {('personaggio', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='personaggio',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='personaggi_base', through='personaggi.PersonaggioStatisticaBase', to='personaggi.statistica'),
        ),
    ]
