# Generated by Django 5.0.7 on 2026-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0098_personaggiostatisticabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='cancellato_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messaggio',
            name='letto_staff',
            field=models.BooleanField(default=False),
        ),
    ]
