# Generated by Django 5.0.7 on 2026-01-23 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0100_messaggio_in_risposta_a_mittente_personaggio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transazionesospesa',
            options={'ordering': ['-data_ultima_modifica'], 'verbose_name': 'Transazione Sospesa', 'verbose_name_plural': 'Transazioni Sospese'},
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='data_chiusura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='data_ultima_modifica',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_ricevute', to='personaggi.personaggio'),
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='iniziatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_iniziate', to='personaggi.personaggio'),
        ),
        migrations.AlterField(
            model_name='transazionesospesa',
            name='mittente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_in_uscita_sospese', to='personaggi.inventario'),
        ),
        migrations.AlterField(
            model_name='transazionesospesa',
            name='oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggetto'),
        ),
        migrations.AlterField(
            model_name='transazionesospesa',
            name='richiedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transazioni_in_entrata_sospese', to='personaggi.personaggio'),
        ),
        migrations.AlterField(
            model_name='transazionesospesa',
            name='stato',
            field=models.CharField(choices=[('IN_ATTESA', 'In Attesa'), ('ACCETTATA', 'Accettata'), ('RIFIUTATA', 'Rifiutata'), ('CHIUSA', 'Chiusa')], default='IN_ATTESA', max_length=20),
        ),
        migrations.CreateModel(
            name='PropostaTransazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crediti_da_dare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crediti_da_ricevere', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('messaggio', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('is_attiva', models.BooleanField(default=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_transazioni', to='personaggi.personaggio')),
                ('oggetti_da_dare', models.ManyToManyField(blank=True, related_name='proposte_oggetti_dati', to='personaggi.oggetto')),
                ('oggetti_da_ricevere', models.ManyToManyField(blank=True, related_name='proposte_oggetti_ricevuti', to='personaggi.oggetto')),
                ('transazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte', to='personaggi.transazionesospesa')),
            ],
            options={
                'verbose_name': 'Proposta Transazione',
                'verbose_name_plural': 'Proposte Transazioni',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='ultima_proposta_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transazione_destinatario_attiva', to='personaggi.propostatransazione'),
        ),
        migrations.AddField(
            model_name='transazionesospesa',
            name='ultima_proposta_iniziatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transazione_iniziatore_attiva', to='personaggi.propostatransazione'),
        ),
        migrations.AddIndex(
            model_name='propostatransazione',
            index=models.Index(fields=['transazione', 'autore', 'is_attiva'], name='personaggi__transaz_5eb465_idx'),
        ),
    ]
