# Generated by Django 5.0.7 on 2026-02-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0101_alter_transazionesospesa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_innesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_inn', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Innesto'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_mod', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Mod'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_mutazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_mut', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Mutazione'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_creazione_oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_ogg', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Oggetto (Materia)'),
        ),
    ]
