# Generated by Django 5.0.7 on 2026-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0102_punteggio_stat_costo_creazione_innesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaggiotessitura',
            options={'verbose_name': 'Personaggio - Tessitura', 'verbose_name_plural': 'Personaggio - Tessiture'},
        ),
        migrations.AddField(
            model_name='personaggiotessitura',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Preferita'),
        ),
        migrations.AlterUniqueTogether(
            name='personaggiotessitura',
            unique_together={('personaggio', 'tessitura')},
        ),
    ]
