# Generated by GPT-5.2 on 2026-03-30

import uuid

import colorfield.fields
import django.db.models.deletion
import icon_widget.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personaggi", "0121_statistica_frt_risorsa_pool"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticaContainer",
            fields=[
                ("sync_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nome", models.CharField(max_length=90)),
                ("sigla", models.CharField(blank=True, max_length=10, null=True)),
                ("ordine", models.IntegerField(default=0)),
                ("colore", colorfield.fields.ColorField(default="#1976D2", image_field=None, max_length=18)),
                ("icona", icon_widget.fields.CustomIconField(blank=True, max_length=255, null=True)),
                ("icona_nome_originale", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "render_in_primarie",
                    models.BooleanField(
                        default=True,
                        help_text="Se attivo, il contenitore viene renderizzato nella sezione 'Statistiche' della scheda.",
                        verbose_name="Mostra in Statistiche (primarie)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="personaggi.statisticacontainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenitore Statistiche",
                "verbose_name_plural": "Contenitori Statistiche",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="StatisticaContainerItem",
            fields=[
                ("sync_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ordine", models.IntegerField(default=0)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="personaggi.statisticacontainer",
                    ),
                ),
                (
                    "statistica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_containers",
                        to="personaggi.statistica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistica in contenitore",
                "verbose_name_plural": "Statistiche in contenitori",
                "ordering": ["container__ordine", "ordine", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="statisticacontaineritem",
            constraint=models.UniqueConstraint(fields=("container", "statistica"), name="uniq_stat_container_item"),
        ),
    ]

