# --- REINDIRIZZAMENTO HTTP -> HTTPS ---
server {
    listen 80;
    server_name localhost www.kor35.it www.k-o-r-35.it kor35.ddns.net;
    return 301 https://$host$request_uri;
}

# --- BLOCCO HTTPS: DOMINI DI PRODUZIONE (Forte) ---
server {
    listen 443 ssl;
    server_name www.kor35.it www.k-o-r-35.it;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # Include le regole comuni
    include /etc/nginx/conf.d/common_locations.snippets;
}

# --- BLOCCO HTTPS: DOMINIO DDNS (Casa) ---
server {
    listen 443 ssl;
    server_name kor35.ddns.net;

    ssl_certificate /etc/nginx/certs_ddns/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs_ddns/privkey.pem;

    # Include le regole comuni
    include /etc/nginx/conf.d/common_locations.snippets;
}
