# Generated by Django 5.0.7 on 2026-05-01 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaggi', '0165_qrcode_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoNave',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codice', models.CharField(help_text='Singolo carattere alfanumerico maiuscolo (secondo char del codice).', max_length=1, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comando nave',
                'verbose_name_plural': 'Comandi nave',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='EventoNave',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.TextField(help_text="Testo mostrato al pilota quando l'evento appare.")),
                ('codice_soluzione_esatta', models.CharField(help_text="Codice 3 char che risolve l'evento (es. 'A23').", max_length=3)),
                ('codici_soluzione_parziale', models.JSONField(blank=True, default=list, help_text='Lista di pattern parziali ammessi, jolly "_". Es. ["A_3","_B5"].')),
                ('durata_base_secondi', models.PositiveIntegerField(default=20, help_text="Tempo di countdown a DEFCON 0; ridotto man mano che la gravita' sale.")),
                ('peso_random', models.PositiveIntegerField(default=10, help_text="Peso relativo per la scelta random (maggiore = piu' frequente).")),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento nave',
                'verbose_name_plural': 'Eventi nave',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SequenzaVolo',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('decollo', 'Decollo'), ('atterraggio', 'Atterraggio')], db_index=True, max_length=16)),
                ('nome', models.CharField(blank=True, default='', max_length=80)),
                ('codici', models.JSONField(default=list, help_text="Lista ordinata di codici 3-char. Es. ['A12','B34','C56'].")),
                ('attiva', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Sequenza di volo',
                'verbose_name_plural': 'Sequenze di volo',
                'ordering': ['tipo', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilotConsoleToken',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('revocato_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pilota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_tokens', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Token console pilota',
                'verbose_name_plural': 'Token console pilota',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessioneVolo',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('idle', 'A terra'), ('decollo', 'Decollo in corso'), ('volo', 'In volo'), ('atterraggio', 'Atterraggio in corso'), ('arrivata', 'Arrivata'), ('crashed', 'Precipitata')], db_index=True, default='idle', max_length=16)),
                ('defcon', models.PositiveIntegerField(default=0)),
                ('durata_pianificata_secondi', models.PositiveIntegerField(default=600)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('decollo_completato_at', models.DateTimeField(blank=True, null=True)),
                ('atterraggio_iniziato_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('decollo_idx', models.PositiveIntegerField(default=0)),
                ('atterraggio_idx', models.PositiveIntegerField(default=0)),
                ('next_event_at', models.DateTimeField(blank=True, null=True)),
                ('pilota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_volo', to='personaggi.personaggio')),
                ('prefettura_arrivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voli_in_arrivo', to='personaggi.prefettura')),
                ('prefettura_partenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voli_in_partenza', to='personaggi.prefettura')),
            ],
            options={
                'verbose_name': 'Sessione di volo',
                'verbose_name_plural': 'Sessioni di volo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoAttivoSessione',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField()),
                ('esito', models.CharField(choices=[('pending', 'In attesa'), ('risolto', 'Risolto'), ('parziale', 'Parziale'), ('fallito', 'Fallito'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=16)),
                ('risolto_at', models.DateTimeField(blank=True, null=True)),
                ('codice_inserito', models.CharField(blank=True, default='', max_length=8)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='istanze', to='pilotaggio.eventonave')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_attivi', to='pilotaggio.sessionevolo')),
            ],
            options={
                'verbose_name': 'Evento attivo',
                'verbose_name_plural': 'Eventi attivi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SottosistemaNave',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codice', models.CharField(help_text='Singolo carattere alfanumerico maiuscolo (primo char del codice comando).', max_length=1, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('durata_ripristino_secondi', models.PositiveIntegerField(default=60, help_text='Tempo di attesa dopo scansione 0RI prima che il sottosistema torni online.')),
                ('attivo', models.BooleanField(default=True)),
                ('a_vista', models.OneToOneField(blank=True, help_text='A_vista collegata: il QrCode su questa A_vista permette guasto/ripristino.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sottosistema_nave', to='personaggi.a_vista')),
            ],
            options={
                'verbose_name': 'Sottosistema nave',
                'verbose_name_plural': 'Sottosistemi nave',
                'ordering': ['codice'],
            },
        ),
        migrations.AddField(
            model_name='eventonave',
            name='sottosistema',
            field=models.ForeignKey(blank=True, help_text='Se collegato, il guasto del sottosistema impatta su questo evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='pilotaggio.sottosistemanave'),
        ),
        migrations.CreateModel(
            name='StatoSottosistemaSessione',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('online', models.BooleanField(default=True)),
                ('guasto_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_at', models.DateTimeField(blank=True, null=True)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati_sottosistemi', to='pilotaggio.sessionevolo')),
                ('sottosistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stati_runtime', to='pilotaggio.sottosistemanave')),
            ],
            options={
                'verbose_name': 'Stato sottosistema in sessione',
                'verbose_name_plural': 'Stati sottosistemi in sessione',
            },
        ),
        migrations.CreateModel(
            name='TentativoCodice',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codice', models.CharField(max_length=8)),
                ('esito', models.CharField(max_length=24)),
                ('defcon_pre', models.IntegerField(default=0)),
                ('defcon_post', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('evento_attivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativi', to='pilotaggio.eventoattivosessione')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativi', to='pilotaggio.sessionevolo')),
            ],
            options={
                'verbose_name': 'Tentativo codice',
                'verbose_name_plural': 'Tentativi codice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionevolo',
            index=models.Index(fields=['pilota', 'stato'], name='pilotaggio__pilota__6a36aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevolo',
            index=models.Index(fields=['stato', 'next_event_at'], name='pilotaggio__stato_ca7a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoattivosessione',
            index=models.Index(fields=['sessione', 'esito'], name='pilotaggio__session_034dac_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoattivosessione',
            index=models.Index(fields=['esito', 'deadline_at'], name='pilotaggio__esito_a79fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='statosottosistemasessione',
            index=models.Index(fields=['sessione', 'online'], name='pilotaggio__session_e242b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statosottosistemasessione',
            unique_together={('sessione', 'sottosistema')},
        ),
    ]
