# Generated by Django 5.0.7 on 2026-05-01 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotaggio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntensitaComando',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valore', models.PositiveSmallIntegerField(help_text="Intensita' numerica usata come terzo carattere (0..9).", unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=80)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Intensita comando',
                'verbose_name_plural': 'Intensita comandi',
                'ordering': ['valore'],
            },
        ),
    ]
