# Generated by Django 5.0.7 on 2026-05-01 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0165_qrcode_inventory_fields'),
        ('pilotaggio', '0002_intensitacomando'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotConsoleLoginTicket',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codice', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('token_console', models.CharField(blank=True, default='', max_length=64)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('pilota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_login_tickets', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Ticket login console',
                'verbose_name_plural': 'Ticket login console',
                'ordering': ['-created_at'],
            },
        ),
    ]
