# Generated by Django 5.0

import uuid
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def seed_stati_allerta(apps, schema_editor):
    M = apps.get_model("pilotaggio", "StatoAllertaPilot")
    rows = [
        (0, "Calmo", "#22c55e", 60, 90, 22, False),
        (1, "Attenzione", "#84cc16", 52, 78, 20, False),
        (2, "Instabile", "#eab308", 45, 68, 18, False),
        (3, "Critico", "#f97316", 35, 55, 16, False),
        (4, "Grave", "#ef4444", 25, 42, 14, False),
        (5, "Estremo", "#b91c1c", 15, 28, 12, False),
        (6, "Nave abbattuta", "#7f1d1d", 8, 12, 5, True),
    ]
    for livello, nome, colore, fmin, fmax, tris, abb in rows:
        M.objects.update_or_create(
            livello=livello,
            defaults={
                "nome": nome,
                "colore": colore,
                "frequenza_evento_min_sec": fmin,
                "frequenza_evento_max_sec": fmax,
                "tempo_risoluzione_secondi": tris,
                "equivale_nave_abbattuta": abb,
            },
        )


def unseed(apps, schema_editor):
    M = apps.get_model("pilotaggio", "StatoAllertaPilot")
    M.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pilotaggio", "0004_eventonave_codici_precipizio"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatoAllertaPilot",
            fields=[
                (
                    "sync_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "livello",
                    models.PositiveSmallIntegerField(
                        help_text="Allineato al DEFCON runtime (0..5 in volo; 6 = oltre soglia / precipizio).",
                        unique=True,
                        validators=[
                            MinValueValidator(0),
                            MaxValueValidator(6),
                        ],
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "colore",
                    models.CharField(
                        default="#888888",
                        help_text="Colore CSS (#RRGGBB) per la console.",
                        max_length=7,
                    ),
                ),
                (
                    "frequenza_evento_min_sec",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Estremo inferiore dell'intervallo (secondi) prima del prossimo evento.",
                    ),
                ),
                (
                    "frequenza_evento_max_sec",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Estremo superiore dell'intervallo (secondi) prima del prossimo evento.",
                    ),
                ),
                (
                    "tempo_risoluzione_secondi",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Durata countdown (secondi) per risolvere un evento mentre si e' in questo livello.",
                    ),
                ),
                (
                    "equivale_nave_abbattuta",
                    models.BooleanField(
                        default=False,
                        help_text="Se vero: questo livello descrive la nave precipitata (crash). Solo uno tra 0..6.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stato allerta console",
                "verbose_name_plural": "Stati allerta console",
                "ordering": ["livello"],
            },
        ),
        migrations.RunPython(seed_stati_allerta, unseed),
    ]
