# Generated by Django 5.0.7 on 2026-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotaggio', '0013_runtime_alarm_audio_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoattivosessione',
            name='esito',
            field=models.CharField(choices=[('pending', 'In attesa'), ('risolto', 'Risolto'), ('parziale', 'Parziale'), ('fallito', 'Fallito'), ('timeout', 'Timeout'), ('precipizio', 'Precipizio')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventonave',
            name='codici_soluzione_parziale',
            field=models.JSONField(blank=True, default=list, help_text='Pattern parziali: jolly "_" (es. ["A_3","_B5"]) o intervallo terza cifra (es. ["ML(4-9)"]).'),
        ),
    ]
