# Generated by Django 5.0.7 on 2026-05-05 14:25

import pilotaggio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotaggio', '0020_sottosistema_effetti_comandi_critici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottosistemanave',
            name='colori_per_livello',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_colori_livello, help_text="Colore HEX per ogni livello 0..9 (es. {'0':'#ffffff',...})."),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='effetti_espulsione_json',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_effetti_espulsione, help_text="Effetti percentuali quando si attiva 'espelli'."),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='effetti_guasto_json',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_effetti_guasto, help_text='Effetto applicato quando il sottosistema va guasto. Chiavi: tipo, valore, target_codice.'),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='effetti_inversione_json',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_effetti_inversione, help_text="Effetti percentuali quando si attiva 'inverti'."),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='guasto_percent_per_livello',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_curve_guasto, help_text="Probabilita' guasto in percentuale per livello 0..9 (chiavi stringa)."),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='ripristino_percent_per_livello',
            field=models.JSONField(blank=True, default=pilotaggio.models._default_curve_zero, help_text="Probabilita' ripristino automatico in percentuale per tick per livello 0..9."),
        ),
    ]
