# Allinea lo state delle migrazioni ai modelli (drift segnalato a ogni deploy).

# Generated by Django 5.0.7 on 2026-10-07 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotaggio', '0046_protocollo_campione_audio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statosottosistemanave',
            new_name='pilotaggio__online_f8585e_idx',
            old_name='pilotaggio__online__nave_idx',
        ),
        migrations.RenameIndex(
            model_name='statosottosistemanave',
            new_name='pilotaggio__espulso_93028b_idx',
            old_name='pilotaggio__espulso_nave_idx',
        ),
        migrations.RenameIndex(
            model_name='vocediariovolo',
            new_name='pilotaggio__session_a08a60_idx',
            old_name='pilotaggio__session_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='vocediariovolo',
            new_name='pilotaggio__session_558837_idx',
            old_name='pilotaggio__session_7c3e91_idx',
        ),
        migrations.AlterField(
            model_name='eventonave',
            name='durata_base_secondi',
            field=models.PositiveIntegerField(default=20, help_text='Deprecato: la durata runtime deriva da StatoAllerta.tempo_risoluzione_secondi.'),
        ),
        migrations.AlterField(
            model_name='eventonave',
            name='durata_tick',
            field=models.CharField(default='4', help_text='Durata evento in tick: "N" fisso oppure "A-B" (random inclusivo tra A e B).', max_length=16),
        ),
        migrations.AlterField(
            model_name='pilotconsoleloginticket',
            name='ruolo',
            field=models.CharField(choices=[('navigazione', 'Console Navigazione'), ('ingegneria', 'Console Ingegneria'), ('scientifica', 'Console Scientifica'), ('comunicazioni', 'Console Comunicazioni')], default='navigazione', help_text='Console destinataria del ticket login inverso.', max_length=16),
        ),
        migrations.AlterField(
            model_name='pilotruntimeconfig',
            name='comunicazioni_console_abilitata',
            field=models.BooleanField(default=False, help_text='Abilita console /pilot/?screen=comunicazioni. Se attiva, gli allarmi cromatici escono dalla plancia.'),
        ),
        migrations.AlterField(
            model_name='pilotruntimeconfig',
            name='comunicazioni_stat_accesso_sigla',
            field=models.CharField(default='0CO', help_text='Sigla statistica accesso console comunicazioni (es. 0CO>0).', max_length=3),
        ),
        migrations.AlterField(
            model_name='pilotruntimeconfig',
            name='scientifica_console_abilitata',
            field=models.BooleanField(default=False, help_text='Abilita console /pilot/?screen=scientifica (spettrografia Fase 1).'),
        ),
        migrations.AlterField(
            model_name='protocollocomunicazione',
            name='testo',
            field=models.TextField(blank=True, default='', help_text='Messaggio ai membri della KORP. Segnaposto: {sottosistema} {evento}.'),
        ),
        migrations.AlterField(
            model_name='scientificostatonave',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sottosistemanave',
            name='requisiti_ricarica_json',
            field=models.JSONField(blank=True, default=list, help_text='Vincoli ricarica: come riparazione + campo ricarica (energia storage o carburante).'),
        ),
        migrations.AlterField(
            model_name='statoallertapilot',
            name='frequenza_evento_max_sec',
            field=models.PositiveIntegerField(default=90, help_text="Solo se probabilita_evento_per_tick=0: estremo superiore (secondi) dell'intervallo casuale prima del prossimo evento."),
        ),
        migrations.AlterField(
            model_name='statoallertapilot',
            name='frequenza_evento_min_sec',
            field=models.PositiveIntegerField(default=60, help_text="Solo se probabilita_evento_per_tick=0: estremo inferiore (secondi) dell'intervallo casuale prima del prossimo evento."),
        ),
        migrations.AlterField(
            model_name='statoallertapilot',
            name='tempo_risoluzione_secondi',
            field=models.PositiveIntegerField(default=20, help_text="Durata in secondi di ogni tick motore mentre c'e' un evento attivo (in viaggio regolare si usa tick_interval_secondi in Runtime Console). Durata totale evento in secondi = tick evento × questo valore."),
        ),
    ]
