
"""
Django settings for kor35 project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ
# env = environ.Env()
# environ.Env.read_env()




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# MODIFICA QUESTA RIGA: Digli di cercare il file esattamente nella BASE_DIR
environ.Env.read_env(BASE_DIR / '.env')

# Capisce se siamo su DigitalOcean o sul Raspberry
CURRENT_ENV = env('ENVIRONMENT', default='production')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2v412!5-=9cils@7_78wzzssrnkf*5)(%z2a6d*z2!3khn1w9c'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = [
    'www.k-o-r-35.it',
    '127.0.0.1', 
    'www.kor35.it', 
    'app.kor35.it', 
    'app.k-o-r-35.it',
    'localhost',
    'kor35.ddns.net',
    '192.168.1.200',
    '192.168.1.50',
                 ]

if CURRENT_ENV == 'raspberry_docker':
    ALLOWED_HOSTS.extend(['*']) # O metti l'IP specifico es: '192.168.1.100'
    CORS_ALLOW_ALL_ORIGINS = True

# prova 

# Application definition


INSTALLED_APPS = [
    'daphne',
	# 'djangocms_admin_style', #cms
	'admin_interface', #admin interface
	'colorfield', 
	"dj_iconify.apps.DjIconifyConfig",
	"django_icon_picker",    
 	'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'personaggi.apps.PersonaggiConfig', #personaggi
	# 'oggetti.apps.OggettiConfig', #oggetti
    'gestione_plot.apps.GestionePlotConfig', #gestione plot
    'social.apps.SocialConfig', # social
	'django.contrib.sites',
	'cms', #cms
	'menus', #cms
	'treebeard', #cms
	'sekizai', #cms
	'easy_thumbnails', #cms/filer
	'filer', #cms
	'allauth',  #allauth
	'allauth.account',  #allauth
	'allauth.socialaccount',  #allauth
	'allauth.socialaccount.providers.google',  #allauth
	# 'cms_kor',
	'django_summernote', # Django-sumernote 28/01/2025
    'rest_framework', # Django REST Framework
    'rest_framework.authtoken', # Django REST Framework Token Authentication
	'corsheaders', # Django CORS Headers
	# 'django_yarnpkg', # django-yarnpkg
	'icon_widget', # icon widget
    'channels',
    'webpush',
    'oauth2_provider',
	
]

# sezione per django_cms

SITE_ID = 1

#CMS_MIGRATION_USER:ID=""

LANGUAGES = [
	('it', 'Italian'),
	('en', 'English'),
	('de', 'German'),
	]

X_FRAME_OPTIONS = 'SAMEORIGIN'

CMS_TEMPLATES = [
	('base.html', 'Home page template'),
	('home.html', 'Vecchio home template'),
	('default.html', 'Default template'),
	]


MEDIA_URL = "/media/"

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_ROOT = '/var/www/django/media'

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

# fine sezione


# Configurazione WebPush
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BIOIApSIeJdV1tp5iVxyLtm8KzM43_AQWV2ymS4iMjkIG1R5g399o6WRdZJY-xcUBZPyJ7EFRVgWqlbalOkGSYw",
    "VAPID_PRIVATE_KEY": "YP8GJDCiP3vGzZp-0ue9lsxK7IFZ5B1OR_TUupfd5pY",
    "VAPID_ADMIN_EMAIL": "mailto:postmaster@k-o-r-35.it",
}

MIDDLEWARE = [
   'django.middleware.security.SecurityMiddleware',
   'django.contrib.sessions.middleware.SessionMiddleware',
   'corsheaders.middleware.CorsMiddleware',  # Django CORS Headers
   'django.middleware.common.CommonMiddleware',
   'django.middleware.csrf.CsrfViewMiddleware',
   'django.contrib.auth.middleware.AuthenticationMiddleware',
   'oauth2_provider.middleware.OAuth2TokenMiddleware',
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.locale.LocaleMiddleware', #cms
	'cms.middleware.utils.ApphookReloadMiddleware', #cms
	'cms.middleware.user.CurrentUserMiddleware', #cms
	'cms.middleware.page.CurrentPageMiddleware', #cms
	'cms.middleware.toolbar.ToolbarMiddleware', #cms
	'cms.middleware.language.LanguageCookieMiddleware', #cms
    'allauth.account.middleware.AccountMiddleware', #allauth
]

ROOT_URLCONF = 'kor35.urls'

# OAUTH2 conf section
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
}

# CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for CORS
CORS_ALLOWED_ORIGINS = [
    "https://www.k-o-r-35.it",     # La tua app React in produzione
    "https://localhost:5173",      # Il tuo server di sviluppo React (Vite)
    # Aggiungi anche http se lo usi in sviluppo
    "http://localhost:5173",
    "https://app.k-o-r-35.it",
    "https://kor35.it",
    "https://www.kor35.it",
    "https://app.kor35.it",
    "http://kor35.it",
    "http://www.kor35.it",
    "http://app.kor35.it",
    "https://social.kor35.it",
    "https://social.k-o-r-35.it", 
    "https://kor35.ddns.net",      
    "http://127.0.0.1:8080",
    "http://localhost:8080",
]

# CORS: senza regex così gli header vengono inviati per tutte le risposte.
# Gli origin consentiti sono comunque solo CORS_ALLOWED_ORIGINS.
# Se in produzione il preflight OPTIONS non arriva a Django (es. nginx), aggiungere
# in nginx: add_header 'Access-Control-Allow-Origin' $http_origin always; (e gestione OPTIONS).
# CORS_URLS_REGEX = r'^/(api/|webpush)/.*$'


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # <-- FONDAMENTALE per il Token Auth
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
                'kor35.context_processors.build_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'kor35.wsgi.application'
ASGI_APPLICATION = 'kor35.asgi.application'


# ASGI settings for Channels

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env('REDIS_HOST', default='127.0.0.1'), 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        # IL TRUCCO È QUI: se non trova la variabile, usa 'db' invece di '127.0.0.1'
        'HOST': os.environ.get('DB_HOST', 'db'), 
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# Edge sync settings (Master <-> Replica)
# Replica: imposta EDGE_SYNC_URL (URL assoluto dell'endpoint Master) e EDGE_SYNC_TOKEN uguale al Master.
EDGE_SYNC_URL = env("EDGE_SYNC_URL", default="").strip()
EDGE_SYNC_TOKEN = env("EDGE_SYNC_TOKEN", default="").strip()
EDGE_NODE_NAME = env("EDGE_NODE_NAME", default="master")
EDGE_SYNC_STATE_FILE = env(
    "EDGE_SYNC_STATE_FILE",
    default=str(BASE_DIR / ".edge_sync_state.json"),
)
# Risposta JSON con messaggio errore DB completo (endpoint protetto da EdgeToken)
EDGE_SYNC_VERBOSE_ERRORS = env.bool("EDGE_SYNC_VERBOSE_ERRORS", default=True)

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
	'allauth.account.auth_backends.AuthenticationBackend', #allauth
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'it'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# yarnpkg settings
# NODE_MODULES_ROOT = os.path.join(BASE_DIR, 'node_modules')
# YARN_PATH = '/usr/bin/yarn'
# YARN_PACKAGE_JSON_PATH = BASE_DIR / 'package.json'  
# YARN_INSTALLED_APPS = [
#   "@iconify/json",
# ]


# iconify settings

ICONIFY_JSON_ROOT = os.path.join(BASE_DIR.parent, 'iconify', 'json')


# Icon Picker settings

ICON_PICKER_PATH = 'media'
ICON_PICKER_COLOR = "#00bcc9"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"

# Se siamo sul Raspberry Pi (Docker)
if CURRENT_ENV == 'raspberry_docker':
    STATIC_ROOT = '/app/static'
    MEDIA_ROOT = '/app/media'
# Altrimenti usa i percorsi di DigitalOcean
else:
    STATIC_ROOT = '/var/www/django/static'
    MEDIA_ROOT = '/var/www/django/media'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_yarnpkg.finders.NodeModulesFinder',
]

# STATICFILES_DIRS = [
#     BASE_DIR / "static", 
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CMS_CONFIRM_VERSION4 = True

# Google OAuth: imposta GOOGLE_OAUTH_CLIENT_ID e GOOGLE_OAUTH_CLIENT_SECRET nel file .env
SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'APP': {
			'client_id': env('GOOGLE_OAUTH_CLIENT_ID', default=''),
			'secret': env('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
			'key': ''
		},
		'SCOPE': [
			'profile',
			'email',
		],
		'AUTH_PARAMS': {
			'access_type': 'online',
		},
	'OAUTH_PKCE_ENABLED': True,
	}
}

# Email settings
# Ensure you have the SMTP_EMAIL environment variable set in your .env file
SMTP_EMAIL = env("SMTP_EMAIL")
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = False	
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = SMTP_EMAIL


# admin_interface settings
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

def _split_origins_env(value: str):
    """Lista origini da variabile env separata da virgole (es. mirror su LAN / Pi come AP)."""
    if not value or not str(value).strip():
        return []
    return [o.strip() for o in str(value).split(",") if o.strip()]


CSRF_TRUSTED_ORIGINS = [
    "https://www.k-o-r-35.it",
    "https://localhost:5173",  # Vite dev (HTTPS)
    "http://localhost:5173",  # Vite dev (HTTP)
    "https://app.k-o-r-35.it",
    "https://app.kor35.it",
    "https://www.kor35.it",
    "https://social.k-o-r-35.it",
    "https://social.kor35.it",
    "https://kor35.ddns.net",
    "http://kor35.ddns.net",  # mirror LAN spesso in HTTP
    "http://127.0.0.1:8080",
    "http://localhost:8080",
]
# Mirror / Pi come access point: aggiungi l’URL esatto che vedi nel browser (schema+host+porta).
# Esempio: EXTRA_CSRF_TRUSTED_ORIGINS=http://192.168.4.1,http://192.168.4.1:80
CSRF_TRUSTED_ORIGINS += _split_origins_env(env("EXTRA_CSRF_TRUSTED_ORIGINS", default=""))

CORS_ALLOWED_ORIGINS += _split_origins_env(env("EXTRA_CORS_ALLOWED_ORIGINS", default=""))

# Django dietro Nginx reverse proxy (HTTPS terminato su Nginx).
# Fondamentale per admin/sessioni/CSRF quando si accede via dominio esterno (es. kor35.ddns.net).
if CURRENT_ENV == "raspberry_docker":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
