services:
  db:
    container_name: kor35_devhome_db
    volumes:
      - ./nginx-docker/postgres_data:/var/lib/postgresql/data

  redis:
    container_name: kor35_devhome_redis

  backend:
    container_name: kor35_devhome_backend
    volumes:
      - ../../backend:/app
      - ./nginx-docker/static_data:/app/static
      - ./nginx-docker/media_data:/app/media

  daphne:
    container_name: kor35_devhome_daphne
    volumes:
      - ../../backend:/app
      - ./nginx-docker/static_data:/app/static
      - ./nginx-docker/media_data:/app/media

  frontend:
    container_name: kor35_devhome_frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx-docker/nginx_conf_wsl:/etc/nginx/conf.d
      - ./nginx-docker/react_build:/usr/share/nginx/html
      - ./nginx-docker/static_data:/app/static
      - ./nginx-docker/media_data:/app/media
