# Generated by Django 4.2.4 on 2023-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caratteristiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome della Caratteristica')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('sigla', models.TextField(max_length=3, verbose_name='Sigla')),
            ],
        ),
    ]
