# Generated by Django 4.2.4 on 2023-11-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0003_abilita_abilita_punteggio_abilita_requisito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell_elemento',
            name='abilita',
        ),
        migrations.AddField(
            model_name='spell_elemento',
            name='elemento',
            field=models.ForeignKey(default=1111111, limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spell',
            name='elementi',
            field=models.ManyToManyField(help_text="Elementi requisito dell'incantesimo", limit_choices_to={'tipo': 'EL'}, related_name='spells', through='personaggi.spell_elemento', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='spell_elemento',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.spell'),
        ),
    ]
