# Generated by Django 5.0.7 on 2024-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0006_punteggio_caratteristica_alter_spell_mattone_mattone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punteggio',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Punteggio', 'verbose_name_plural': 'Punteggi'},
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura')], max_length=2, verbose_name='Tipo di punteggio'),
        ),
    ]
