# Generated by Django 5.0.7 on 2025-01-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0010_delete_tabellapluginmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilita_tier',
            options={'ordering': ['ordine', 'abilita__nome'], 'verbose_name': 'Abilità - Tier', 'verbose_name_plural': 'Abilità - Tiers'},
        ),
        migrations.AddField(
            model_name='abilita_tier',
            name='ordine',
            field=models.IntegerField(default=10, verbose_name='Ordine in tabella'),
        ),
    ]
