# Generated by Django 5.0.7 on 2025-10-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0011_alter_abilita_tier_options_abilita_tier_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='aura',
            field=models.ForeignKey(default=29, limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='aura_spell', to='personaggi.punteggio'),
            preserve_default=False,
        ),
    ]
