# Generated by Django 5.0.7 on 2025-11-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0014_abilita_tier_costo_crediti_alter_abilita_tier_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistica',
            name='valore_base_predefinito',
            field=models.IntegerField(default=0, help_text='Valore BASE di default per questa statistica (per i VALORI INIZIALI).'),
        ),
    ]
