# Generated by Django 5.0.7 on 2025-11-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0015_statistica_valore_base_predefinito'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistica',
            name='parametro',
            field=models.CharField(blank=True, help_text="La variabile da usare nel testo, es. 'pv' (senza parentesi graffe).", max_length=10, null=True, unique=True),
        ),
    ]
