# Generated by Django 5.0.7 on 2025-11-07 13:59

import django.db.models.deletion
import django.utils.timezone
import personaggi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0018_abilitastatistica_tipo_modificatore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaPersonaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Standard', max_length=100, unique=True)),
                ('crediti_iniziali', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caratteristiche_iniziali', models.IntegerField(default=8)),
                ('giocante', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipologia Personaggio',
                'verbose_name_plural': 'Tipologie Personaggio',
            },
        ),
        migrations.CreateModel(
            name='PuntiCaratteristicaMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.IntegerField()),
                ('descrizione', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_pc', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Movimento Punti Caratteristica',
                'verbose_name_plural': 'Movimenti Punti Caratteristica',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='personaggio',
            name='tipologia',
            field=models.ForeignKey(default=personaggi.models.get_default_tipologia, on_delete=django.db.models.deletion.PROTECT, related_name='personaggi', to='personaggi.tipologiapersonaggio'),
        ),
    ]
