# Generated by Django 5.0.7 on 2025-11-14 14:20

import django_icon_picker.field
import icon_widget.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0024_tier_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='icona_old',
            field=django_icon_picker.field.IconField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='icona',
            field=icon_widget.fields.CustomIconField(blank=True, max_length=255, null=True),
        ),
    ]
