# Generated by Django 5.0.7 on 2025-11-20 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0031_alter_punteggio_options_punteggio_ordine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('membri', models.ManyToManyField(blank=True, related_name='gruppi_appartenenza', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Gruppo di Personaggi',
                'verbose_name_plural': 'Gruppi di Personaggi',
            },
        ),
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_messaggio', models.CharField(choices=[('BROAD', 'Broadcast (Tutti)'), ('GROUP', 'Gruppo'), ('INDV', 'Individuale')], default='BROAD', max_length=5)),
                ('titolo', models.CharField(max_length=150)),
                ('testo', models.TextField()),
                ('data_invio', models.DateTimeField(default=django.utils.timezone.now)),
                ('salva_in_cronologia', models.BooleanField(default=True, help_text='Se disattivato, il messaggio non appare nella cronologia pubblica del gioco.')),
                ('destinatario_gruppo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaggi_ricevuti_gruppo', to='personaggi.gruppo')),
                ('destinatario_personaggio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaggi_ricevuti_individuali', to='personaggi.personaggio')),
                ('mittente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi Inviati',
                'ordering': ['-data_invio'],
            },
        ),
    ]
