# Generated by Django 5.0.7 on 2025-11-21 23:53

import colorfield.fields
import django.db.models.deletion
import personaggi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0035_alter_abilita_prerequisito_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infusione',
            name='statistiche',
        ),
        migrations.AlterUniqueTogether(
            name='tessiturastatistica',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tessiturastatistica',
            name='limit_a_aure',
        ),
        migrations.RemoveField(
            model_name='tessiturastatistica',
            name='limit_a_elementi',
        ),
        migrations.RemoveField(
            model_name='tessiturastatistica',
            name='statistica',
        ),
        migrations.RemoveField(
            model_name='tessiturastatistica',
            name='tessitura',
        ),
        migrations.RemoveField(
            model_name='tessitura',
            name='statistiche',
        ),
        migrations.AlterModelOptions(
            name='caratteristicamodificatore',
            options={},
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='usa_limitazione_aura',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Aura'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='usa_limitazione_elemento',
            field=models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='aura',
            field=models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='mattoni_aura', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='caratteristica_associata',
            field=models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, related_name='mattoni_caratteristica', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='descrizione_mattone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='descrizione_metatalento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='funzionamento_metatalento',
            field=models.CharField(choices=[('NE', 'Nessun Effetto'), ('VP', 'Valore per Punteggio'), ('TX', 'Solo Testo Addizionale'), ('LV', 'Solo abilità con livello pari o inferiore')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='mattoni_statistiche', through='personaggi.MattoneStatistica', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='testo_addizionale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='tipologia',
            field=models.ForeignKey(default=personaggi.models.get_default_tipologia, on_delete=django.db.models.deletion.PROTECT, related_name='personaggi', to='personaggi.tipologiapersonaggio'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='caratteristica_relativa',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punteggi_caratteristica', to='personaggi.punteggio'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='colore',
            field=colorfield.fields.ColorField(default='#1976D2', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='is_generica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='is_mattone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='is_soprannaturale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='ordine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione'), ('CU', 'Culto'), ('VI', 'Via'), ('AR', 'Arte'), ('AR', 'Archetipo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='parametro',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tabella',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tipo',
            field=models.CharField(choices=[('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3'), ('T4', 'Tier 4')], max_length=2),
        ),
        migrations.DeleteModel(
            name='InfusioneStatistica',
        ),
        migrations.DeleteModel(
            name='TessituraStatistica',
        ),
    ]
