# Generated by Django 5.0.7 on 2025-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0040_abilitastatistica_condizione_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattone',
            options={'ordering': ['tipo', 'ordine', 'nome'], 'verbose_name': 'Mattone', 'verbose_name_plural': 'Mattoni'},
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='mattoni_obbligatori',
            field=models.ManyToManyField(blank=True, help_text='Le tessiture DEVONO contenere almeno uno di questi mattoni per poter essere apprese.', related_name='obbligatori_in_modelli', to='personaggi.mattone', verbose_name='Mattoni Obbligatori'),
        ),
        migrations.AlterField(
            model_name='modelloaura',
            name='mattoni_proibiti',
            field=models.ManyToManyField(blank=True, related_name='proibiti_in_modelli', to='personaggi.mattone', verbose_name='Mattoni Proibiti'),
        ),
    ]
