# Generated by Django 5.0.7 on 2025-11-23 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0041_alter_mattone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelloaura',
            name='elemento_secondario',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'EL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelli_secondari', to='personaggi.punteggio'),
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='usa_condizione_caratt',
            field=models.BooleanField(default=False, help_text='Se attivo, le formule extra appaiono solo se i requisiti sotto sono soddisfatti.', verbose_name='Richiede Condizione per F. Caratt.'),
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='usa_condizione_doppia',
            field=models.BooleanField(default=False, help_text='Se attivo, la doppia formula appare solo se i requisiti sotto sono soddisfatti.', verbose_name='Richiede Condizione per Doppia'),
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='usa_doppia_formula',
            field=models.BooleanField(default=False, verbose_name='Abilita Doppia Formula'),
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='usa_formula_per_caratteristica',
            field=models.BooleanField(default=False, verbose_name='Abilita Formula per Caratteristica'),
        ),
        migrations.CreateModel(
            name='ModelloAuraRequisitoCaratt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_caratt_rel', to='personaggi.modelloaura')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
            ],
            options={
                'verbose_name': 'Requisito Formula x Caratteristica',
                'verbose_name_plural': 'Requisiti Formula x Caratteristica',
            },
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='requisiti_caratt',
            field=models.ManyToManyField(blank=True, related_name='modelli_req_caratt', through='personaggi.ModelloAuraRequisitoCaratt', to='personaggi.punteggio'),
        ),
        migrations.CreateModel(
            name='ModelloAuraRequisitoDoppia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_doppia_rel', to='personaggi.modelloaura')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
            ],
            options={
                'verbose_name': 'Requisito Doppia Formula',
                'verbose_name_plural': 'Requisiti Doppia Formula',
            },
        ),
        migrations.AddField(
            model_name='modelloaura',
            name='requisiti_doppia',
            field=models.ManyToManyField(blank=True, related_name='modelli_req_doppia', through='personaggi.ModelloAuraRequisitoDoppia', to='personaggi.punteggio'),
        ),
    ]
