# Generated by Django 5.0.7 on 2025-11-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0042_modelloaura_elemento_secondario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='costo_crediti',
            field=models.IntegerField(default=0, verbose_name='Valore in Crediti'),
        ),
    ]
