# Generated by Django 5.0.7 on 2025-11-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0044_modelloaura_usa_condizione_mattone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelloaura',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione Breve'),
        ),
    ]
