# Generated by Django 5.0.7 on 2025-11-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0045_modelloaura_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INF', 'Infusione'), ('TES', 'Tessitura')], max_length=3)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('VALUTAZIONE', 'In Valutazione'), ('APPROVATA', 'Approvata'), ('RIFIUTATA', 'Rifiutata')], default='BOZZA', max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(verbose_name='Ragionamento/Descrizione')),
                ('costo_invio_pagato', models.IntegerField(default=0, help_text="Crediti spesi per l'invio")),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio', models.DateTimeField(blank=True, null=True)),
                ('note_staff', models.TextField(blank=True, null=True)),
                ('aura', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposte_aura', to='personaggi.punteggio')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_tecniche', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Proposta Tecnica',
                'verbose_name_plural': 'Proposte Tecniche',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='PropostaTecnicaMattone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('mattone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.mattone')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.propostatecnica')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='mattoni',
            field=models.ManyToManyField(related_name='proposte_in_cui_usato', through='personaggi.PropostaTecnicaMattone', to='personaggi.mattone'),
        ),
    ]
