# Generated by Django 5.0.7 on 2025-11-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0046_propostatecnica_propostatecnicamattone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='proposta_creazione',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infusione_generata', to='personaggi.propostatecnica', verbose_name='Proposta Originale'),
        ),
        migrations.AddField(
            model_name='tessitura',
            name='proposta_creazione',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tessitura_generata', to='personaggi.propostatecnica', verbose_name='Proposta Originale'),
        ),
    ]
