# Generated by Django 5.0.7 on 2025-11-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0047_infusione_proposta_creazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetturaMessaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letto', models.BooleanField(default=False)),
                ('data_lettura', models.DateTimeField(blank=True, null=True)),
                ('cancellato', models.BooleanField(default=False)),
                ('messaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati_lettura', to='personaggi.messaggio')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_stati', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Stato Lettura Messaggio',
                'verbose_name_plural': 'Stati Lettura Messaggi',
                'unique_together': {('messaggio', 'personaggio')},
            },
        ),
    ]
