# Generated by Django 5.0.7 on 2025-11-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0048_letturamessaggio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilita_requisito',
            name='requisito',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ('CA', 'CO')}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
    ]
