# Generated by Django 5.0.7 on 2025-11-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0049_alter_abilita_requisito_requisito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilita_prerequisito',
            options={'verbose_name': 'Abilità richieste come prerequisito di acquisto'},
        ),
        migrations.AlterModelOptions(
            name='abilita_punteggio',
            options={'verbose_name': "Punteggi assegnati dall'abilità"},
        ),
        migrations.AlterModelOptions(
            name='abilita_requisito',
            options={'verbose_name': 'Punteggi richiesti come requisito di acquisto'},
        ),
        migrations.AlterField(
            model_name='abilita_requisito',
            name='requisito',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ('CA', 'CO', 'ST')}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio'),
        ),
    ]
