# Generated by Django 5.0.7 on 2025-12-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0055_punteggio_stat_costo_acquisto_infusione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OggettoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('tipo_oggetto', models.CharField(choices=[('FIS', 'Oggetto Fisico'), ('MAT', 'Materia (Mondana)'), ('MOD', 'Mod (Tecnologica)'), ('INN', 'Innesto (Tecnologico)'), ('MUT', 'Mutazione (Innata)')], default='FIS', max_length=3)),
                ('is_tecnologico', models.BooleanField(default=False)),
                ('costo', models.IntegerField(default=0, verbose_name='Costo in Crediti')),
                ('attacco_base', models.CharField(blank=True, help_text='Es. 2d6', max_length=50, null=True)),
                ('in_vendita', models.BooleanField(default=True, verbose_name='Visibile in Negozio')),
                ('classe_oggetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.classeoggetto', verbose_name='Classe (es. Fucile, Spada)')),
            ],
            options={
                'verbose_name': 'Oggetto Base (Listino)',
                'verbose_name_plural': 'Oggetti Base (Listino)',
                'ordering': ['tipo_oggetto', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='oggetto',
            name='oggetto_base_generatore',
            field=models.ForeignKey(blank=True, help_text='Se creato dal negozio, punta al template originale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istanze_generate', to='personaggi.oggettobase'),
        ),
        migrations.CreateModel(
            name='OggettoBaseModificatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=0)),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3)),
                ('oggetto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggettobase')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Modificatore Template',
                'verbose_name_plural': 'Modificatori Template',
            },
        ),
        migrations.AddField(
            model_name='oggettobase',
            name='statistiche_modificatori',
            field=models.ManyToManyField(blank=True, related_name='template_modificatori', through='personaggi.OggettoBaseModificatore', to='personaggi.statistica'),
        ),
        migrations.CreateModel(
            name='OggettoBaseStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('oggetto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.oggettobase')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Statistica Base Template',
                'verbose_name_plural': 'Statistiche Base Template',
            },
        ),
        migrations.AddField(
            model_name='oggettobase',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='template_base', through='personaggi.OggettoBaseStatisticaBase', to='personaggi.statistica'),
        ),
    ]
