# Generated by Django 5.0.7 on 2025-12-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0056_oggettobase_oggetto_oggetto_base_generatore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infusione',
            name='mattoni',
        ),
        migrations.RemoveField(
            model_name='propostatecnica',
            name='mattoni',
        ),
        migrations.RemoveField(
            model_name='tessitura',
            name='mattoni',
        ),
        migrations.AddField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, help_text="Formula di attacco se l'oggetto è un'arma. ", max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='aura_infusione',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposte_infusione', to='personaggi.punteggio'),
        ),
        migrations.CreateModel(
            name='InfusioneCaratteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='personaggi.infusione')),
            ],
            options={
                'unique_together': {('infusione', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='infusione',
            name='caratteristiche',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'CA'}, related_name='infusioni_utilizzatrici', through='personaggi.InfusioneCaratteristica', to='personaggi.punteggio'),
        ),
        migrations.CreateModel(
            name='PropostaTecnicaCaratteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='personaggi.propostatecnica')),
            ],
            options={
                'ordering': ['caratteristica__nome'],
                'unique_together': {('proposta', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='propostatecnica',
            name='caratteristiche',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'CA'}, related_name='proposte_in_cui_usato', through='personaggi.PropostaTecnicaCaratteristica', to='personaggi.punteggio'),
        ),
        migrations.CreateModel(
            name='TessituraCaratteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=1)),
                ('caratteristica', models.ForeignKey(limit_choices_to={'tipo': 'CA'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio')),
                ('tessitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='personaggi.tessitura')),
            ],
            options={
                'unique_together': {('tessitura', 'caratteristica')},
            },
        ),
        migrations.AddField(
            model_name='tessitura',
            name='caratteristiche',
            field=models.ManyToManyField(limit_choices_to={'tipo': 'CA'}, related_name='tessiture_utilizzatrici', through='personaggi.TessituraCaratteristica', to='personaggi.punteggio'),
        ),
    ]
