# Generated by Django 5.0.7 on 2025-12-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0058_remove_tessituramattone_mattone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilita_prerequisito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_punteggio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='abilita_requisito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aura',
            options={'verbose_name': 'Aura', 'verbose_name_plural': 'Aure'},
        ),
        migrations.AlterModelOptions(
            name='caratteristica',
            options={'verbose_name': 'Caratteristica', 'verbose_name_plural': 'Caratteristiche'},
        ),
        migrations.AlterModelOptions(
            name='modelloaurarequisitocaratt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelloaurarequisitodoppia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelloaurarequisitomattone',
            options={},
        ),
        migrations.AlterField(
            model_name='abilitastatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Es. caratt>6', max_length=255, null=True, verbose_name='Condizione'),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='mattone',
            name='dichiarazione',
            field=models.TextField(blank=True, null=True, verbose_name='Dichiarazione'),
        ),
        migrations.AlterField(
            model_name='mattonestatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Es. caratt>6', max_length=255, null=True, verbose_name='Condizione'),
        ),
        migrations.AlterField(
            model_name='oggettostatistica',
            name='condizione_text',
            field=models.CharField(blank=True, help_text='Es. caratt>6', max_length=255, null=True, verbose_name='Condizione'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Formula'),
        ),
    ]
