# Generated by Django 5.0.7 on 2025-12-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0059_alter_abilita_prerequisito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_infusione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_inf', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Inf)'),
        ),
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_tessitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_tes', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Tes)'),
        ),
    ]
