# Generated by Django 5.0.7 on 2025-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0062_remove_oggetto_elementi_oggettocaratteristica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richiestaassemblaggio',
            options={'ordering': ['-data_creazione'], 'verbose_name': 'Richiesta Lavoro', 'verbose_name_plural': 'Richieste Lavoro'},
        ),
        migrations.AddField(
            model_name='richiestaassemblaggio',
            name='tipo_operazione',
            field=models.CharField(choices=[('INST', 'Installazione'), ('RIMO', 'Rimozione')], default='INST', max_length=4, verbose_name='Tipo Operazione'),
        ),
    ]
