# Generated by Django 5.0.7 on 2025-12-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0064_richiestaassemblaggio_infusione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgiaturaincorso',
            name='destinatario_finale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forgiature_in_arrivo', to='personaggi.personaggio'),
        ),
    ]
