# Generated by Django 5.0.7 on 2025-12-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0067_infusione_slot_corpo_permessi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfusioneStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_limitazione_aura', models.BooleanField(default=False, verbose_name='Usa Limitazione Aura')),
                ('usa_limitazione_elemento', models.BooleanField(default=False, verbose_name='Usa Limitazione Elemento')),
                ('usa_condizione_text', models.BooleanField(default=False, verbose_name='Usa Condizione Testuale')),
                ('condizione_text', models.CharField(blank=True, help_text='Es. caratt>6', max_length=255, null=True, verbose_name='Condizione')),
                ('valore', models.IntegerField(default=0)),
                ('tipo_modificatore', models.CharField(choices=[('ADD', 'Additivo (+N)'), ('MOL', 'Moltiplicativo (xN)')], default='ADD', max_length=3)),
                ('infusione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.infusione')),
                ('limit_a_aure', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite')),
                ('limit_a_elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Statistica Infusione',
                'verbose_name_plural': 'Statistiche Infusione',
                'unique_together': {('infusione', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='infusione',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='infusione_statistiche', through='personaggi.InfusioneStatistica', to='personaggi.statistica'),
        ),
    ]
