# Generated by Django 5.0.7 on 2025-12-08 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0068_infusionestatistica_infusione_statistiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgiaturaincorso',
            name='data_inizio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
