# Generated by Django 5.0.7 on 2025-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0072_punteggio_nome_tipo_aumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='nome_tessitura',
            field=models.CharField(blank=True, help_text='Es. Mod, Materia', max_length=50, null=True),
        ),
    ]
