# Generated by Django 5.0.7 on 2025-12-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0081_alter_oggetto_attacco_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilita',
            name='aura_riferimento',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratti_collegati', to='personaggi.punteggio'),
        ),
        migrations.AddField(
            model_name='abilita',
            name='is_tratto_aura',
            field=models.BooleanField(default=False, verbose_name="È un Tratto d'Aura?"),
        ),
        migrations.AddField(
            model_name='abilita',
            name='livello_riferimento',
            field=models.IntegerField(default=0, help_text='A quale livello di questa aura appartiene questo tratto?'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='attacco_base',
            field=models.CharField(blank=True, help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ConfigurazioneLivelloAura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.IntegerField(default=1, help_text='A che valore di aura si sblocca questa scelta?')),
                ('nome_step', models.CharField(help_text='Es. Archetipo, Sottotipo, Dono Divino', max_length=50)),
                ('descrizione_fluff', models.TextField(blank=True, help_text="Testo descrittivo per l'interfaccia", null=True)),
                ('is_obbligatorio', models.BooleanField(default=True, help_text='Il giocatore DEVE fare una scelta per questo livello?')),
                ('aura', models.ForeignKey(limit_choices_to={'tipo': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='configurazione_livelli', to='personaggi.punteggio')),
            ],
            options={
                'verbose_name': 'Configurazione Livello Aura',
                'verbose_name_plural': 'Configurazioni Livelli Aura',
                'ordering': ['aura', 'livello'],
                'unique_together': {('aura', 'livello')},
            },
        ),
    ]
