# Generated by Django 5.0.7 on 2025-12-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0084_propostatecnica_effetto_propostatecnica_prerequisiti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='impostazioni_ui',
            field=models.JSONField(blank=True, default=dict, verbose_name='Impostazioni UI'),
        ),
    ]
