# Generated by Django 5.0.7 on 2026-01-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0087_tipologiatimer_timerqrcode_statotimerattivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerqrcode',
            name='ultima_attivazione',
            field=models.DateField(blank=True, null=True, verbose_name='Data Ultima Attivazione'),
        ),
    ]
