# Generated by Django 5.0.7 on 2026-01-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0089_propostatecnica_livello_proposto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_cerimoniale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_cer', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Cer)'),
        ),
    ]
