# Generated by Django 5.0.7 on 2026-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0093_alter_tier_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dichiarazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DAN_NRM', 'Danno - Normale'), ('DAN_ELM', 'Danno - Elementale'), ('DAN_SUF', 'Danno - Suffissi'), ('EFF_DUR', 'Effetto - Durata'), ('EFF_IST', 'Effetto - Istantaneo'), ('SUF_RNG', 'Suffisso - Rango'), ('AFF_EFF', 'Affisso - Efficacia'), ('SUF_TRG', 'Suffisso - Bersaglio'), ('PRE_MOL', 'Prefisso - Moltiplicativo'), ('PRM_CAP', 'Premessa - Capacità'), ('PRM_SRC', 'Premessa - Sorgente'), ('PRM_LVL', 'Premessa - Livello'), ('PRM_TIP', 'Premessa - Tipologia'), ('PRE_FRM', 'Prefisso - Forma'), ('EFF_SPC', 'Effetto - Speciale')], db_index=True, max_length=7, verbose_name='Tipologia Dichiarazione')),
                ('testo', models.CharField(max_length=255, unique=True, verbose_name='Valore / Testo')),
            ],
            options={
                'verbose_name': 'Dichiarazione / Glossario',
                'verbose_name_plural': 'Dichiarazioni e Glossario',
                'ordering': ['tipo', 'testo'],
            },
        ),
    ]
