# Generated by Django 5.0.7 on 2026-01-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0095_alter_dichiarazione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='is_staff_message',
            field=models.BooleanField(default=False),
        ),
    ]
