# Generated by Django 5.0.7 on 2026-04-10 15:30

import colorfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0131_recuperorisorsaattivo_pause_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroupsyncstate',
            options={'verbose_name': 'Sync State Gruppo', 'verbose_name_plural': 'Sync State Gruppi'},
        ),
        migrations.AlterModelOptions(
            name='authusersyncstate',
            options={'verbose_name': 'Sync State Utente', 'verbose_name_plural': 'Sync State Utenti'},
        ),
        migrations.AlterModelOptions(
            name='korp',
            options={'verbose_name': 'KORP', 'verbose_name_plural': 'KORPS'},
        ),
        migrations.AlterField(
            model_name='era',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eraabilita',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personaggioabilita',
            name='origine',
            field=models.CharField(choices=[('acquisto', 'Acquisto'), ('era_default', 'Era (default)'), ('regione_default', 'Regione (default)')], default='acquisto', max_length=20),
        ),
        migrations.AlterField(
            model_name='prefettura',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='tipo',
            field=models.CharField(choices=[('CA', 'Caratteristica'), ('ST', 'Statistica'), ('EL', 'Elemento'), ('AU', 'Aura'), ('CO', 'Condizione'), ('CU', 'Culto'), ('VI', 'Via'), ('AR', 'Arte'), ('AT', 'Archetipo'), ('MA', 'Mattone'), ('CS', 'Castone'), ('ND', 'Nodo'), ('KA', 'Kata')], max_length=2),
        ),
        migrations.AlterField(
            model_name='regione',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='regioneabilita',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statisticacontainer',
            name='colore',
            field=colorfield.fields.ColorField(default='#1976D2', image_field=None, max_length=25, samples=None),
        ),
    ]
