# Generated by Django 5.0.7 on 2026-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0136_default_formula_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilita',
            name='effetto_uso_risorsa',
            field=models.JSONField(blank=True, help_text='Opzionale. stat_sigla = sigla pool (es. FRT; per chakra CHA). Alias legacy CHK viene mappato su CHA.', null=True, verbose_name="Effetto all'uso risorsa"),
        ),
        migrations.AlterField(
            model_name='abilita',
            name='recupero_risorsa',
            field=models.JSONField(blank=True, help_text='Opzionale. Es. {"rigenerazioni":[{"stat_sigla":"CHA","ogni_minuti":10,"step":1}]} — stat_sigla = risorsa pool (PV, PA, PS, CHA, FRT, …). CHK in JSON è accettato come alias di CHA.', null=True, verbose_name='Recupero risorsa'),
        ),
    ]
