# Generated by Django 5.0.7 on 2026-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0137_alter_abilita_effetto_uso_risorsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumabilepersonaggio',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}', null=True),
        ),
        migrations.AlterField(
            model_name='effettocasuale',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}', help_text='Stesso formato della descrizione. Obbligatorio se tipologia=Tessitura.', null=True),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}', max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}', null=True, verbose_name='Formula'),
        ),
    ]
