# Generated by Django 5.0.7 on 2026-04-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0139_merge_0137_formula_flag_0138_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistica',
            options={'ordering': ['-formula', 'ordine', 'nome'], 'verbose_name': 'Statistica', 'verbose_name_plural': 'Statistiche'},
        ),
    ]
