# Generated by Django 5.0.7 on 2026-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0141_alter_statistica_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichiarazione',
            name='tipo',
            field=models.CharField(choices=[('DAN_NRM', 'Danno - Normale'), ('DAN_ELM', 'Danno - Elementale'), ('DAN_SUF', 'Danno - Suffissi'), ('EFF_DUR', 'Effetto - Durata'), ('EFF_IST', 'Effetto - Istantaneo'), ('SUF_RNG', 'Suffisso - Rango'), ('AFF_EFF', 'Affisso - Efficacia'), ('SUF_TRG', 'Suffisso - Bersaglio'), ('PRE_MOL', 'Prefisso - Moltiplicativo'), ('PRM_CAP', 'Premessa - Capacità'), ('PRM_SRC', 'Premessa - Sorgente'), ('PRM_LVL', 'Premessa - Livello'), ('PRM_TIP', 'Premessa - Tipologia'), ('PRE_FRM', 'Prefisso - Forma'), ('EFF_SPC', 'Effetto - Speciale'), ('GLOS', 'Glossario')], db_index=True, max_length=7, verbose_name='Tipologia Dichiarazione'),
        ),
    ]
