# Generated by Codex on 2026-04-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personaggi", "0142_alter_dichiarazione_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcanaSSOIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_sub", models.CharField(db_index=True, max_length=128, unique=True)),
                ("email_snapshot", models.EmailField(blank=True, default="", max_length=254)),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcana_sso_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Identita Arcana SSO",
                "verbose_name_plural": "Identita Arcana SSO",
            },
        ),
    ]
