# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personaggi", "0143_arcanassoidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcanassoidentity",
            name="ad_profile_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
