# Generated by Django 5.0.7 on 2026-04-16 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0150_campagne_multicampagna_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campagnafeaturepolicy',
            name='camp_feat_unique',
        ),
        migrations.RemoveConstraint(
            model_name='campagnautente',
            name='camp_user_unique',
        ),
        migrations.RenameIndex(
            model_name='campagnafeaturepolicy',
            new_name='personaggi__campagn_fa07f6_idx',
            old_name='camp_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='campagnafeaturepolicy',
            new_name='personaggi__campagn_84dad4_idx',
            old_name='camp_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='campagnautente',
            new_name='personaggi__campagn_f01dde_idx',
            old_name='camp_user_idx',
        ),
        migrations.RenameIndex(
            model_name='campagnautente',
            new_name='personaggi__user_id_c31427_idx',
            old_name='user_role_idx',
        ),
        migrations.RenameIndex(
            model_name='campagnautente',
            new_name='personaggi__campagn_63472b_idx',
            old_name='camp_role_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campagnafeaturepolicy',
            unique_together={('campagna', 'feature_key')},
        ),
        migrations.AlterUniqueTogether(
            name='campagnautente',
            unique_together={('campagna', 'user')},
        ),
    ]
