# Generated by Django 5.0.7 on 2026-04-26 23:19

import django.db.models.deletion
import personaggi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0155_manifesto_requisiti_innesco_timer_qr_inventario_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innescotimer',
            old_name='avista_ptr',
            new_name='a_vista_ptr',
        ),
        migrations.RenameIndex(
            model_name='qrinventarioscansession',
            new_name='personaggi__user_id_7f4700_idx',
            old_name='qrinv_sess_uqcf',
        ),
        migrations.RenameIndex(
            model_name='qrinventarioscansession',
            new_name='personaggi__persona_10495a_idx',
            old_name='qrinv_sess_pgqr',
        ),
        migrations.RenameIndex(
            model_name='statoinnescotimerpersonaggio',
            new_name='personaggi__persona_024d89_idx',
            old_name='innesco_st_pg_it',
        ),
        migrations.AlterField(
            model_name='innescotimer',
            name='campagna',
            field=models.ForeignKey(default=personaggi.models.get_default_campagna_id, on_delete=django.db.models.deletion.PROTECT, related_name='innesco_timers', to='personaggi.campagna'),
        ),
    ]
