# Generated by Django 5.0.7 on 2026-04-29 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0163_watch_device_mvp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchdevicebinding',
            new_name='personaggi__persona_f951c9_idx',
            old_name='personaggi_w_personag_7adf02_idx',
        ),
        migrations.RenameIndex(
            model_name='watchdevicebinding',
            new_name='personaggi__device__66f316_idx',
            old_name='personaggi_w_device__e43434_idx',
        ),
        migrations.RenameIndex(
            model_name='watchdevicebinding',
            new_name='personaggi__campagn_46531c_idx',
            old_name='personaggi_w_campagn_8dbd66_idx',
        ),
        migrations.RenameIndex(
            model_name='watchdeviceeventlog',
            new_name='personaggi__persona_4aa266_idx',
            old_name='personaggi_w_personag_182502_idx',
        ),
        migrations.RenameIndex(
            model_name='watchdeviceeventlog',
            new_name='personaggi__binding_605cf2_idx',
            old_name='personaggi_w_binding_042f53_idx',
        ),
        migrations.RenameIndex(
            model_name='watchpairingcode',
            new_name='personaggi__device__25505a_idx',
            old_name='personaggi_w_device__f3bfd6_idx',
        ),
        migrations.RenameIndex(
            model_name='watchpairingcode',
            new_name='personaggi__campagn_7bb590_idx',
            old_name='personaggi_w_campagn_d453d2_idx',
        ),
        migrations.AlterField(
            model_name='watchdevicebinding',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='watchdeviceeventlog',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='watchpairingcode',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
