# Generated by Django 5.0.7 on 2026-05-08 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0165_qrcode_inventory_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumabilepersonaggio',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', null=True),
        ),
        migrations.AlterField(
            model_name='effettocasuale',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', help_text='Stesso formato della descrizione. Obbligatorio se tipologia=Tessitura.', null=True),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', null=True, verbose_name='Formula'),
        ),
        migrations.CreateModel(
            name='AbilitaFormulaRule',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codice Identificativo')),
                ('scope', models.CharField(choices=[('ALL', 'Tutto'), ('ATT', 'Solo Attacchi'), ('WEA', 'Solo Tessiture')], default='ALL', max_length=3)),
                ('rule_type', models.CharField(choices=[('SOURCE_OVERRIDE', 'Sostituisci sorgente'), ('AURA_REPLACE', 'Sostituisci aura'), ('AURA_APPEND', 'Aggiungi aura alternativa'), ('ELEMENT_REPLACE', 'Sostituisci elemento')], max_length=30)),
                ('source_label', models.CharField(blank=True, max_length=80, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('abilita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_rules', to='personaggi.abilita')),
                ('from_punteggio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_from', to='personaggi.punteggio')),
                ('to_punteggio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_to', to='personaggi.punteggio')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
