# Generated by Django 5.0.7 on 2026-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0166_alter_consumabilepersonaggio_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_status}{formula_cura}{formula_damage}', help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
    ]
