# Generated by Django 5.0.7 on 2026-05-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0167_alter_infusione_formula_attacco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitaformularule',
            name='from_mattone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_from_mattone', to='personaggi.mattone'),
        ),
        migrations.AddField(
            model_name='abilitaformularule',
            name='to_mattone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_rule_to_mattone', to='personaggi.mattone'),
        ),
    ]
