# Generated by Django 5.0.7 on 2026-05-22 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0172_tecniche_non_acquistabile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistica',
            name='is_costo',
            field=models.BooleanField(default=False, help_text='Se attivo, la statistica può essere scelta nei campi stat_costo_* (costi crafting/acquisto).', verbose_name='Statistica costo'),
        ),
        migrations.AddField(
            model_name='statistica',
            name='is_tempo',
            field=models.BooleanField(default=False, help_text='Se attivo, la statistica può essere scelta nei campi stat_tempo_* (durate crafting).', verbose_name='Statistica tempo'),
        ),
        migrations.AlterField(
            model_name='consumabilepersonaggio',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', null=True),
        ),
        migrations.AlterField(
            model_name='effettocasuale',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', help_text='Stesso formato della descrizione. Obbligatorio se tipologia=Tessitura.', null=True),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', help_text='Es. {rango|:RANGO}{molt|:MOLT}Chop! {dannigen+dannimis|:L}!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_acquisto_cerimoniale',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_cer', to='personaggi.statistica', verbose_name='Stat. Costo Acquisto Cerimoniale'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_acquisto_infusione',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_inf', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_acquisto_tessitura',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_acquisto_tes', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_consumabili',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_stat_costo_consumabili', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Consumabili'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_cerimoniale',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_cer', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Cerimoniale'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_infusione',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_inf', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_innesto',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_inn', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Innesto'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_mod',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_mod', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Mod'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_mutazione',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_mut', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Mutazione'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_oggetto',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_ogg', to='personaggi.statistica', verbose_name='Stat. Costo Creazione Oggetto (Materia)'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_creazione_tessitura',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_creazione_tes', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_forgiatura',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_forgia', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_cerimoniale',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_cer', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Cer)'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_infusione',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_inf', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Inf)'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_costo_invio_proposta_tessitura',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_costo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_costo_invio_prop_tes', to='personaggi.statistica', verbose_name='Stat. Costo Invio Proposta (Tes)'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_tempo_creazione_consumabili',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_tempo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_stat_tempo_creazione_consumabili', to='personaggi.statistica', verbose_name='Stat. Tempo Creazione Consumabili (sec)'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_tempo_forgiatura',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_tempo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_tempo_forgia', to='personaggi.statistica'),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{formula_damage}{formula_cura}{formula_status}', null=True, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='tessituraeffettoruntime',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tessituraoggettoruntime',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
