# Generated by Django 5.0.7 on 2026-05-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0173_statistica_is_costo_statistica_is_tempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistica',
            name='is_numero',
            field=models.BooleanField(default=False, help_text='Se attivo, la statistica può essere scelta nei campi stat_numero_* (quantità, conteggi).', verbose_name='Statistica numero'),
        ),
        migrations.AlterField(
            model_name='punteggio',
            name='stat_numero_consumabili',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_numero': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_stat_numero_consumabili', to='personaggi.statistica', verbose_name='Stat. Numero Consumabili'),
        ),
    ]
