# Generated by Django 5.0.7 on 2026-05-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0174_statistica_is_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio',
            name='stat_durata_consumabili',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_tempo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aure_stat_durata_consumabili', to='personaggi.statistica', verbose_name='Stat. Durata Consumabili (giorni)'),
        ),
    ]
