# Generated by Django 5.0.7 on 2026-05-24 21:39

import django.db.models.deletion
import django.utils.timezone
import personaggi.scommesse_models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0177_propostatecnica_spiegazione_teorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioScommesse',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titolo', models.CharField(blank=True, default='', max_length=160)),
                ('data_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_risoluzione', models.DateTimeField(help_text='Data/ora in cui i risultati diventano visibili ai giocatori.')),
                ('importo_max_senza_codice', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('attivo', models.BooleanField(default=True)),
                ('liquidato', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Calendario scommesse',
                'verbose_name_plural': 'Calendari scommesse',
                'ordering': ['-data_risoluzione'],
            },
        ),
        migrations.CreateModel(
            name='CodiceScommessa',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codice', models.CharField(db_index=True, max_length=5, unique=True)),
                ('usato', models.BooleanField(default=False)),
                ('usato_at', models.DateTimeField(blank=True, null=True)),
                ('allibratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codici_scommessa_generati', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Codice scommessa',
                'verbose_name_plural': 'Codici scommessa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuntataScommessa',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('SINGOLA', 'Singola'), ('COMBINATA', 'Combinata')], default='SINGOLA', max_length=12)),
                ('quota_totale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stato', models.CharField(choices=[('PENDING', 'In attesa'), ('WON', 'Vinta'), ('LOST', 'Persa')], default='PENDING', max_length=10)),
                ('vincita', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('liquidata_at', models.DateTimeField(blank=True, null=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntate', to='personaggi.calendarioscommesse')),
                ('codice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntate', to='personaggi.codicescommessa')),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntate_scommesse', to='personaggi.personaggio')),
            ],
            options={
                'verbose_name': 'Puntata scommessa',
                'verbose_name_plural': 'Puntate scommesse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportScommesse',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('attivo', models.BooleanField(default=True)),
                ('campagna', models.ForeignKey(default=personaggi.scommesse_models.get_default_campagna_id, on_delete=django.db.models.deletion.PROTECT, related_name='sport_scommesse', to='personaggi.campagna')),
            ],
            options={
                'verbose_name': 'Sport scommesse',
                'verbose_name_plural': 'Sport scommesse',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='calendarioscommesse',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendari', to='personaggi.sportscommesse'),
        ),
        migrations.CreateModel(
            name='SquadraScommesse',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('potenza', models.PositiveIntegerField(default=50, help_text='Potenza numerica della squadra (1-999)')),
                ('attiva', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='personaggi.sportscommesse')),
            ],
            options={
                'verbose_name': 'Squadra scommesse',
                'verbose_name_plural': 'Squadre scommesse',
                'ordering': ['sport__nome', 'nome'],
                'unique_together': {('sport', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='IncontroScommesse',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('potenza_casa_effettiva', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('potenza_trasferta_effettiva', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quota_casa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quota_pareggio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quota_trasferta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esito', models.CharField(choices=[('1', '1'), ('2', '2'), ('X', 'X')], max_length=1)),
                ('gol_casa', models.PositiveSmallIntegerField(default=0)),
                ('gol_trasferta', models.PositiveSmallIntegerField(default=0)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incontri', to='personaggi.calendarioscommesse')),
                ('squadra_casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incontri_casa', to='personaggi.squadrascommesse')),
                ('squadra_trasferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incontri_trasferta', to='personaggi.squadrascommesse')),
            ],
            options={
                'verbose_name': 'Incontro scommesse',
                'verbose_name_plural': 'Incontri scommesse',
                'ordering': ['calendario', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='SelezionePuntata',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('esito_scelto', models.CharField(choices=[('1', '1'), ('2', '2'), ('X', 'X')], max_length=1)),
                ('incontro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selezioni_puntate', to='personaggi.incontroscommesse')),
                ('puntata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selezioni', to='personaggi.puntatascommessa')),
            ],
            options={
                'verbose_name': 'Selezione puntata',
                'verbose_name_plural': 'Selezioni puntata',
                'unique_together': {('puntata', 'incontro')},
            },
        ),
    ]
