# Generated by Django 5.0.7 on 2026-05-24 21:57

import django.db.models.deletion
import personaggi.scommesse_models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0178_scommesse_in_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioscommesse',
            name='importo_max_senza_codice',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='ConfigurazioneScommesse',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importo_max_senza_codice_default', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Importo massimo (CR) per scommessa senza codice allibratore (default nuovi calendari).', max_digits=10)),
                ('scadenza_calendario_ore', models.PositiveSmallIntegerField(default=24, help_text='Ore di visibilità del calendario dopo la pubblicazione risultati.')),
                ('commissione_allibratore_pct', models.DecimalField(decimal_places=4, default=Decimal('0.08'), help_text="Frazione dell'importo (es. 0.08 = 8%) accreditata all'allibratore.", max_digits=5)),
                ('margine_book_default', models.DecimalField(decimal_places=4, default=Decimal('1.06'), help_text='Margine del bookmaker sulle quote standard (>1 = house edge).', max_digits=6)),
                ('margine_book_min', models.DecimalField(decimal_places=4, default=Decimal('1.02'), help_text='Margine minimo con codice allibratore (ALL alto).', max_digits=6)),
                ('riduzione_margine_per_punto_all', models.DecimalField(decimal_places=4, default=Decimal('0.015'), help_text='Riduzione margine per ogni punto della statistica ALL.', max_digits=6)),
                ('variabilita_potenza_pct', models.PositiveSmallIntegerField(default=10, help_text='Variabilità ±% applicata alla potenza squadre nel calcolo quote.')),
                ('max_selezioni_combinata', models.PositiveSmallIntegerField(default=8, help_text='Massimo eventi in una scommessa combinata.')),
                ('attiva', models.BooleanField(default=True)),
                ('campagna', models.OneToOneField(default=personaggi.scommesse_models.get_default_campagna_id, on_delete=django.db.models.deletion.CASCADE, related_name='configurazione_scommesse', to='personaggi.campagna')),
            ],
            options={
                'verbose_name': 'Configurazione scommesse',
                'verbose_name_plural': 'Configurazioni scommesse',
            },
        ),
    ]
