# Generated by Django 5.0.7 on 2026-05-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0179_scommesse_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionescommesse',
            name='potenza_delta_sconfitta',
            field=models.PositiveSmallIntegerField(default=2, help_text='Decremento potenza squadra perdente dopo ogni incontro risolto.'),
        ),
        migrations.AddField(
            model_name='configurazionescommesse',
            name='potenza_delta_vittoria',
            field=models.PositiveSmallIntegerField(default=2, help_text='Incremento potenza squadra vincente dopo ogni incontro risolto.'),
        ),
    ]
