# Generated by Django 5.0.7 on 2026-06-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0193_abilitastatistica_bonus_slot_equip'),
        ('personaggi', '0198_instafame_badge_visibile_social'),
    ]

    operations = [
    ]
