# Generated by Django 5.0.7 on 2026-06-19 22:20

import django.db.models.deletion
import personaggi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0203_minigioco_modalita_sblocco'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfusioneCostoAttivazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo', models.PositiveIntegerField(default=1, verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Costo attivazione infusione',
                'verbose_name_plural': 'Costi attivazione infusione',
            },
        ),
        migrations.CreateModel(
            name='TessituraCostoAttivazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo', models.PositiveIntegerField(default=1, verbose_name='Costo')),
            ],
            options={
                'verbose_name': 'Costo attivazione tessitura',
                'verbose_name_plural': 'Costi attivazione tessitura',
            },
        ),
        migrations.AlterModelOptions(
            name='personaggiocarrieramembership',
            options={'ordering': ['-data_da', '-id'], 'verbose_name': 'Membership Carriera', 'verbose_name_plural': 'Membership Carriere'},
        ),
        migrations.RenameIndex(
            model_name='minigiocoqrsession',
            new_name='personaggi__persona_1a5036_idx',
            old_name='personaggi_m_persona_6a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='minigiocoqrsession',
            new_name='personaggi__qr_code_5de9e3_idx',
            old_name='personaggi_m_qr_code_7b1c4e_idx',
        ),
        migrations.AlterField(
            model_name='campagnafeaturepolicy',
            name='feature_key',
            field=models.CharField(choices=[('abilita', 'Abilita'), ('tessiture', 'Tessiture'), ('infusioni', 'Infusioni'), ('oggetti_base', 'Oggetti Base'), ('cerimoniali', 'Cerimoniali'), ('social', 'Social'), ('negozi_mercante', 'Negozi mercante')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='consumabilepersonaggio',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', null=True),
        ),
        migrations.AlterField(
            model_name='effettocasuale',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', help_text='Stesso formato della descrizione. Obbligatorio se tipologia=Tessitura.', null=True),
        ),
        migrations.AlterField(
            model_name='infusione',
            name='formula_attacco',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', max_length=255, null=True, verbose_name='Formula Attacco'),
        ),
        migrations.AlterField(
            model_name='minigiocoqrconfig',
            name='tipi_abilitati',
            field=models.JSONField(blank=True, default=personaggi.models._default_tipi_minigioco_qr, help_text='Pool giochi estratti a caso (sliding_puzzle, memory, simon, …).'),
        ),
        migrations.AlterField(
            model_name='minigiocoqrconfig',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sliding_puzzle', 'Sliding puzzle'), ('memory', 'Memory'), ('rotate_tiles', 'Tessere rotabili'), ('simon', 'Sequenza (Simon)'), ('pattern_lock', 'Pattern lock'), ('pipe_connect', 'Collega i tubi')], default='sliding_puzzle', help_text='Legacy: ignorato se tipi_abilitati è valorizzato.', max_length=32),
        ),
        migrations.AlterField(
            model_name='negoziomercante',
            name='incassa_acquisti_catalogo',
            field=models.BooleanField(default=True, help_text='Se attivo, i CR spesi in acquisti dal catalogo staff entrano nella cassa del negozio.'),
        ),
        migrations.AlterField(
            model_name='negoziomercante',
            name='regole_apertura',
            field=models.JSONField(blank=True, default=dict, help_text='Es. {"modalita":"sempre_aperto"} o fasce orarie / requisiti_extra.'),
        ),
        migrations.AlterField(
            model_name='negoziomercante',
            name='regole_visibilita',
            field=models.JSONField(blank=True, default=dict, help_text='Per negozi corporativi: {"operator":"OR","requisiti":[...]}.'),
        ),
        migrations.AlterField(
            model_name='negoziomercantevoce',
            name='consumabile_tessitura',
            field=models.ForeignKey(blank=True, help_text="Template tessitura per generare il consumabile all'acquisto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_consumabile_negozio', to='personaggi.tessitura'),
        ),
        migrations.AlterField(
            model_name='negoziomercantevoce',
            name='prezzo_crediti',
            field=models.PositiveIntegerField(help_text='Prezzo in crediti per questo negozio (obbligatorio, manuale).'),
        ),
        migrations.AlterField(
            model_name='negoziomercantevoce',
            name='quantita_residua',
            field=models.PositiveIntegerField(blank=True, help_text='Null = illimitato. Per consumabili e cap oggetti base.', null=True),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', help_text='Es. {rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{formula_cura}{formula_status} oppure versione distanza con {danni_distanza}.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oggettobase',
            name='attacco_base',
            field=models.CharField(blank=True, default='{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', help_text='Es. {rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{formula_cura}{formula_status} oppure versione distanza con {danni_distanza}.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tessitura',
            name='formula',
            field=models.TextField(blank=True, default='{formula_type}{rango|:RANGO}{molt|:MOLT}{formula_prefix}{formula_target}{formula_source}{danni_mischia}{danni_distanza}{formula_cura}{formula_status}', null=True, verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='infusionecostoattivazione',
            name='infusione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costi_attivazione', to='personaggi.infusione'),
        ),
        migrations.AddField(
            model_name='infusionecostoattivazione',
            name='statistica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='tessituracostoattivazione',
            name='statistica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica'),
        ),
        migrations.AddField(
            model_name='tessituracostoattivazione',
            name='tessitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costi_attivazione', to='personaggi.tessitura'),
        ),
        migrations.AlterUniqueTogether(
            name='infusionecostoattivazione',
            unique_together={('infusione', 'statistica')},
        ),
        migrations.AlterUniqueTogether(
            name='tessituracostoattivazione',
            unique_together={('tessitura', 'statistica')},
        ),
    ]
