# Generated by Django 5.0.7 on 2026-06-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0204_costi_attivazione_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitastatistica',
            name='solo_oggetto_ospitante',
            field=models.BooleanField(default=False, help_text="Se attivo, il modificatore vale solo per le formule dell'oggetto su cui è montato (o dell'oggetto stesso), non per le statistiche generali del personaggio.", verbose_name='Solo oggetto ospitante'),
        ),
        migrations.AddField(
            model_name='infusionestatistica',
            name='solo_oggetto_ospitante',
            field=models.BooleanField(default=False, help_text="Se attivo, il modificatore vale solo per le formule dell'oggetto su cui è montato (o dell'oggetto stesso), non per le statistiche generali del personaggio.", verbose_name='Solo oggetto ospitante'),
        ),
        migrations.AddField(
            model_name='mattonestatistica',
            name='solo_oggetto_ospitante',
            field=models.BooleanField(default=False, help_text="Se attivo, il modificatore vale solo per le formule dell'oggetto su cui è montato (o dell'oggetto stesso), non per le statistiche generali del personaggio.", verbose_name='Solo oggetto ospitante'),
        ),
        migrations.AddField(
            model_name='oggettobasemodificatore',
            name='solo_oggetto_ospitante',
            field=models.BooleanField(default=False, help_text="Se attivo, il modificatore vale solo per le formule dell'oggetto, non per il personaggio.", verbose_name='Solo oggetto ospitante'),
        ),
        migrations.AddField(
            model_name='oggettostatistica',
            name='solo_oggetto_ospitante',
            field=models.BooleanField(default=False, help_text="Se attivo, il modificatore vale solo per le formule dell'oggetto su cui è montato (o dell'oggetto stesso), non per le statistiche generali del personaggio.", verbose_name='Solo oggetto ospitante'),
        ),
    ]
