# Generated by Django 5.0.7 on 2026-06-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0205_solo_oggetto_ospitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='infusione',
            name='formula_builder_selezioni',
            field=models.JSONField(blank=True, default=dict, help_text='Scelte staff dal costruttore formula (sorgente, tipo danno, ecc.).', verbose_name='Selezioni formula builder'),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='formula_builder_selezioni',
            field=models.JSONField(blank=True, default=dict, help_text='Scelte staff dal costruttore formula (sorgente, tipo danno, ecc.).', verbose_name='Selezioni formula builder'),
        ),
        migrations.AddField(
            model_name='oggettobase',
            name='formula_builder_selezioni',
            field=models.JSONField(blank=True, default=dict, help_text='Scelte staff dal costruttore formula (sorgente, tipo danno, ecc.).', verbose_name='Selezioni formula builder'),
        ),
        migrations.AddField(
            model_name='tessitura',
            name='formula_builder_selezioni',
            field=models.JSONField(blank=True, default=dict, help_text='Scelte staff dal costruttore formula (sorgente, tipo danno, ecc.).', verbose_name='Selezioni formula builder'),
        ),
    ]
