# Generated by Django 5.0.7 on 2026-08-10 13:51

import django.db.models.deletion
import personaggi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0254_regola_pagabile_con_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQrPool',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('attivo', models.BooleanField(db_index=True, default=True)),
                ('minigioco_sezione_attiva', models.BooleanField(default=False, help_text="Se True, la sezione minigiochi governa l'accesso ai QR del pool (salvo override per-QR).")),
                ('minigioco_attivo', models.BooleanField(default=False, help_text="Se True (con sezione attiva), richiede il minigioco prima dell'effetto pool.")),
                ('minigioco_tipi_abilitati', models.JSONField(blank=True, default=personaggi.models._default_tipi_minigioco_pool)),
                ('minigioco_difficolta', models.PositiveSmallIntegerField(default=4)),
                ('minigioco_requisiti_attivazione', models.JSONField(blank=True, default=list)),
                ('minigioco_messaggio_accesso_negato', models.TextField(blank=True, default='')),
                ('minigioco_esclusioni', models.JSONField(blank=True, default=list)),
                ('minigioco_regole_difficolta', models.JSONField(blank=True, default=list)),
                ('minigioco_messaggio_pre', models.TextField(blank=True, default='')),
                ('minigioco_messaggio_vittoria', models.TextField(blank=True, default='')),
                ('minigioco_timer_secondi', models.PositiveIntegerField(blank=True, null=True)),
                ('minigioco_timer_scadenza_azione', models.CharField(choices=[('attiva_qr', 'Attiva il QR'), ('blocca_qr', 'Blocca il QR (non riattivabile)'), ('reset_minigioco', 'Reset minigioco')], default='reset_minigioco', max_length=32)),
                ('minigioco_usa_biblioteca_se_vuota', models.BooleanField(default=True)),
                ('minigioco_modalita_sblocco', models.CharField(choices=[('ogni_scansione', 'Minigioco a ogni scansione'), ('permanente', 'Una volta risolto, per sempre'), ('temporaneo', 'Sblocco temporaneo (N secondi)')], default='permanente', max_length=24)),
                ('minigioco_sblocco_secondi', models.PositiveIntegerField(blank=True, null=True)),
                ('minigioco_immagine', models.ImageField(blank=True, null=True, upload_to='minigioco_qr_pool/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Pool QR randomico',
                'verbose_name_plural': 'Pool QR randomici',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RandomQrPoolEffect',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('testo', 'Testo'), ('nodo', 'Nodo'), ('trappola', 'Trappola'), ('serie', 'Serie')], db_index=True, max_length=16)),
                ('frequenza', models.PositiveIntegerField(default=1, help_text='Peso relativo: più alto = più comune (es. 10 vs 1 → ~10:1).')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('titolo', models.CharField(blank=True, default='', max_length=120)),
                ('testo', models.TextField(blank=True, default='')),
                ('durata_secondi', models.PositiveIntegerField(blank=True, help_text='Solo trappola: durata timer personale (vuoto = solo messaggio).', null=True)),
            ],
            options={
                'verbose_name': 'Effetto pool QR',
                'verbose_name_plural': 'Effetti pool QR',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RandomQrPoolMembership',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership pool QR',
                'verbose_name_plural': 'Membership pool QR',
            },
        ),
        migrations.CreateModel(
            name='SerieAssegnazione',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indice', models.PositiveIntegerField()),
                ('assegnato_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assegnazione serie',
                'verbose_name_plural': 'Assegnazioni serie',
            },
        ),
        migrations.CreateModel(
            name='SerieCollezione',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=120)),
                ('totale', models.PositiveIntegerField(help_text="Numero totale di pezzi unici (N in 'X di N').")),
                ('descrizione', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Serie collezione',
                'verbose_name_plural': 'Serie collezioni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SerieQr',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
            ],
            options={
                'verbose_name': 'QR Serie',
                'verbose_name_plural': 'QR Serie',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.CreateModel(
            name='StatoTrappolaPersonaggio',
            fields=[
                ('sync_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chiave', models.CharField(db_index=True, max_length=64)),
                ('nome', models.CharField(max_length=120)),
                ('testo', models.TextField(blank=True, default='')),
                ('data_fine', models.DateTimeField(verbose_name='Scadenza countdown')),
            ],
            options={
                'verbose_name': 'Stato trappola (personaggio)',
                'verbose_name_plural': 'Stati trappola (personaggio)',
            },
        ),
        migrations.CreateModel(
            name='Trappola',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personaggi.a_vista')),
                ('durata_secondi', models.PositiveIntegerField(blank=True, help_text='Vuoto = solo messaggio descrittivo, senza countdown.', null=True, verbose_name='Durata timer (secondi)')),
            ],
            options={
                'verbose_name': 'Trappola QR',
                'verbose_name_plural': 'Trappole QR',
            },
            bases=('personaggi.a_vista',),
        ),
        migrations.AddField(
            model_name='randomqrpool',
            name='campagna',
            field=models.ForeignKey(default=personaggi.models.get_default_campagna_id, on_delete=django.db.models.deletion.PROTECT, related_name='random_qr_pools', to='personaggi.campagna'),
        ),
        migrations.AddField(
            model_name='randomqrpooleffect',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_effetti', to='personaggi.nodo'),
        ),
        migrations.AddField(
            model_name='randomqrpooleffect',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effetti', to='personaggi.randomqrpool'),
        ),
        migrations.AddField(
            model_name='randomqrpoolmembership',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='personaggi.randomqrpool'),
        ),
        migrations.AddField(
            model_name='randomqrpoolmembership',
            name='qr_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='random_pool_membership', to='personaggi.qrcode'),
        ),
        migrations.AddField(
            model_name='serieassegnazione',
            name='oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serie_assegnazioni', to='personaggi.oggetto'),
        ),
        migrations.AddField(
            model_name='serieassegnazione',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_assegnazioni', to='personaggi.personaggio'),
        ),
        migrations.AddField(
            model_name='serieassegnazione',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serie_assegnazioni', to='personaggi.qrcode'),
        ),
        migrations.AddField(
            model_name='seriecollezione',
            name='campagna',
            field=models.ForeignKey(default=personaggi.models.get_default_campagna_id, on_delete=django.db.models.deletion.PROTECT, related_name='serie_collezioni', to='personaggi.campagna'),
        ),
        migrations.AddField(
            model_name='serieassegnazione',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='personaggi.seriecollezione'),
        ),
        migrations.AddField(
            model_name='randomqrpooleffect',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_effetti', to='personaggi.seriecollezione'),
        ),
        migrations.AddField(
            model_name='serieqr',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_standalone', to='personaggi.seriecollezione'),
        ),
        migrations.AddField(
            model_name='statotrappolapersonaggio',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati_trappola', to='personaggi.personaggio'),
        ),
        migrations.AddField(
            model_name='statotrappolapersonaggio',
            name='trappola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stati_personaggio', to='personaggi.trappola'),
        ),
        migrations.AddIndex(
            model_name='serieassegnazione',
            index=models.Index(fields=['serie', 'indice'], name='personaggi__serie_i_8a905d_idx'),
        ),
        migrations.AddIndex(
            model_name='serieassegnazione',
            index=models.Index(fields=['personaggio', 'serie'], name='personaggi__persona_75205f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serieassegnazione',
            unique_together={('serie', 'indice')},
        ),
        migrations.AddIndex(
            model_name='statotrappolapersonaggio',
            index=models.Index(fields=['personaggio', 'data_fine'], name='personaggi__persona_2fb726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statotrappolapersonaggio',
            unique_together={('personaggio', 'chiave')},
        ),
    ]
