# Generated by Django 4.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personaggi", "0268_sezioni_condizionali"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiamataVocale",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("verso_staff", models.BooleanField(default=False)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("ringing", "In squillo"),
                            ("in_corso", "In corso"),
                            ("rifiutata", "Rifiutata"),
                            ("terminata", "Terminata"),
                            ("persa", "Persa"),
                        ],
                        db_index=True,
                        default="ringing",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accettata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chiamate_vocali_accettate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chiamate_vocali",
                        to="personaggi.campagna",
                    ),
                ),
                (
                    "chiamante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chiamate_uscenti",
                        to="personaggi.personaggio",
                    ),
                ),
                (
                    "chiamato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chiamate_entranti",
                        to="personaggi.personaggio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chiamata vocale",
                "verbose_name_plural": "Chiamate vocali",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chiamatavocale",
            index=models.Index(fields=["stato", "created_at"], name="personaggi__stato_c4a1e0_idx"),
        ),
    ]
