# Generated by Django 5.0.7 on 2026-10-07 10:24

# Allinea lo state delle migrazioni ai modelli (drift segnalato a ogni deploy).

import uuid
from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaggi', '0296_innesco_timer_cariche_giorno'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartacollezionabile',
            new_name='personaggi__campagn_09f056_idx',
            old_name='personaggi__campagn_8f4a21_idx',
        ),
        migrations.RenameIndex(
            model_name='cartacollezionabile',
            new_name='personaggi__campagn_58e3e9_idx',
            old_name='personaggi__campagn_2c9e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='cartacollezionabile',
            new_name='personaggi__campagn_38d2ec_idx',
            old_name='personaggi__campagn_esp_idx',
        ),
        migrations.RenameIndex(
            model_name='cartaerrata',
            new_name='personaggi__campagn_311465_idx',
            old_name='personaggi_campagn_6eebf1_idx',
        ),
        migrations.RenameIndex(
            model_name='cartaposseduta',
            new_name='personaggi__persona_17557e_idx',
            old_name='personaggi__persona_7d3b12_idx',
        ),
        migrations.RenameIndex(
            model_name='chiamatavocale',
            new_name='personaggi__stato_ff38b2_idx',
            old_name='personaggi__stato_c4a1e0_idx',
        ),
        migrations.RenameIndex(
            model_name='documentoarchiviato',
            new_name='personaggi__persona_4a52e3_idx',
            old_name='personaggi__persona_docarch_idx',
        ),
        migrations.RenameIndex(
            model_name='espansionecarte',
            new_name='personaggi__campagn_4df4ab_idx',
            old_name='personaggi__campagn_esp_att_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmdevicetoken',
            new_name='personaggi__user_id_89dbdb_idx',
            old_name='personaggi__user_id_fcm_idx',
        ),
        migrations.RenameIndex(
            model_name='negoziomercanteprestito',
            new_name='personaggi__negozio_48f279_idx',
            old_name='personaggi__negozio_a8f1c2_idx',
        ),
        migrations.RenameIndex(
            model_name='negoziomercanteprestito',
            new_name='personaggi__oggetto_31a482_idx',
            old_name='personaggi__oggetto_b3d4e5_idx',
        ),
        migrations.AlterField(
            model_name='campagnafeaturepolicy',
            name='feature_key',
            field=models.CharField(choices=[('abilita', 'Abilita'), ('tessiture', 'Tessiture'), ('infusioni', 'Infusioni'), ('oggetti_base', 'Oggetti Base'), ('cerimoniali', 'Cerimoniali'), ('social', 'Social'), ('negozi_mercante', 'Negozi mercante'), ('carte_collezionabili', 'Carte collezionabili')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='carrieraabilita',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carrieraabilita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartacollezionabile',
            name='bonus_equip',
            field=models.JSONField(blank=True, default=dict, help_text='Bonus equip: reliquiario {"stat_sigla":"FOR","valore":1}; duello {"forza":1,"robustezza_se_leader":2} o {"duello":[{"stat":"forza","valore":2},{"stat":"robustezza","valore":2,"se_leader":true}]}'),
        ),
        migrations.AlterField(
            model_name='cartaerrata',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartareliquiariostatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite'),
        ),
        migrations.AlterField(
            model_name='cartareliquiariostatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti'),
        ),
        migrations.AlterField(
            model_name='cartareliquiariostatistica',
            name='valore',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valore additivo (+N) o moltiplicativo (xN, es. 0.5 per -50%).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='cartearenaruleset',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartegiocodefinizione',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartemsepackageimport',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carteplatformexchangejob',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carteplatformexchangejob',
            name='tipo',
            field=models.CharField(choices=[('import_mse_set', 'Import set MSE'), ('export_mse_set', 'Export set MSE'), ('import_mse_style', 'Import style MSE'), ('export_mse_style', 'Export style MSE'), ('export_playable_spec', 'Export playable spec Arena')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='carteplatformgiocatore',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartestudiotemplate',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comboreliquiariostatistica',
            name='limit_a_aure',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'AU'}, related_name='%(class)s_limit_aure', to='personaggi.punteggio', verbose_name='Aure consentite'),
        ),
        migrations.AlterField(
            model_name='comboreliquiariostatistica',
            name='limit_a_elementi',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, related_name='%(class)s_limit_elementi', to='personaggi.punteggio', verbose_name='Elementi consentiti'),
        ),
        migrations.AlterField(
            model_name='comboreliquiariostatistica',
            name='valore',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valore additivo (+N) o moltiplicativo (xN, es. 0.5 per -50%).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='configurazionescommesse',
            name='soglia_vincita_rilevante',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Oltre questa soglia, per puntata si ritira al massimo questo importo in contanti (resto resta in riserva).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='keywordcarta',
            name='codice',
            field=models.CharField(db_index=True, help_text='Identificatore univoco per campagna, es. MUTAZIONE o EVOCAZIONE', max_length=40),
        ),
        migrations.AlterField(
            model_name='keywordcarta',
            name='nome',
            field=models.CharField(help_text='Testo da cercare nel testo carta. Usa [X], [Y], … per parametri (es. "Mutazione [X]" corrisponde a "Mutazione 0").', max_length=80),
        ),
        migrations.AlterField(
            model_name='keywordcarta',
            name='reminder_breve',
            field=models.CharField(blank=True, default='', help_text='Promemoria inline; placeholder [X] sostituiti come nel testo regola.', max_length=120),
        ),
        migrations.AlterField(
            model_name='keywordcarta',
            name='testo_regola',
            field=models.TextField(help_text='Testo completo al tap/click; stessi placeholder del nome (es. …costo [X].).'),
        ),
        migrations.AlterField(
            model_name='seriecollezione',
            name='totale',
            field=models.PositiveIntegerField(help_text="Numero totale di pezzi (N in 'X di N')."),
        ),
    ]
