# Generated by Django 5.0.7 on 2026-01-04 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0001_initial'),
        ('personaggi', '0090_punteggio_stat_costo_invio_proposta_cerimoniale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MostroTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('punti_vita_base', models.IntegerField(default=1)),
                ('armatura_base', models.IntegerField(default=0)),
                ('guscio_base', models.IntegerField(default=0)),
                ('note_generali', models.TextField(blank=True, help_text='Descrizione fisica o comportamento standard')),
            ],
            options={
                'verbose_name': 'Template Mostro',
                'verbose_name_plural': 'A. Template Mostri',
            },
        ),
        migrations.AlterModelOptions(
            name='pngassegnato',
            options={'ordering': ['staffer', 'ordine_uscita'], 'verbose_name': 'PnG Assegnato', 'verbose_name_plural': '5. PnG Assegnati'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Quest', 'verbose_name_plural': '3. Quests'},
        ),
        migrations.AlterModelOptions(
            name='questvista',
            options={'verbose_name': 'Oggetto Vista Quest', 'verbose_name_plural': '6. Oggetti Vista'},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='mostri_generici',
        ),
        migrations.AlterField(
            model_name='evento',
            name='partecipanti',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipologia__giocante': True}, related_name='eventi_partecipati', to='personaggi.personaggio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pc_guadagnati',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='staff_assegnato',
            field=models.ManyToManyField(related_name='eventi_gestiti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giornoevento',
            name='sinossi_breve',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pngassegnato',
            name='ordine_uscita',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pngassegnato',
            name='personaggio',
            field=models.ForeignKey(limit_choices_to={'tipologia__giocante': False}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio'),
        ),
        migrations.AlterField(
            model_name='questvista',
            name='qr_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.qrcode'),
        ),
        migrations.AlterField(
            model_name='questvista',
            name='tipo',
            field=models.CharField(choices=[('INV', 'Inventario'), ('MAN', 'Manifesto')], max_length=3),
        ),
        migrations.CreateModel(
            name='AttaccoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_attacco', models.CharField(max_length=100)),
                ('descrizione_danno', models.CharField(help_text='Es: 3 Fisici, Atterramento...', max_length=200)),
                ('ordine', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacchi', to='gestione_plot.mostrotemplate')),
            ],
            options={
                'verbose_name': 'Attacco Template',
                'verbose_name_plural': 'B. Attacchi Template',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='QuestMostro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti_vita', models.IntegerField(help_text='Copiati dal template, ma modificabili per questa istanza')),
                ('armatura', models.IntegerField(default=0)),
                ('guscio', models.IntegerField(default=0)),
                ('note_per_staffer', models.TextField(blank=True, help_text='Note specifiche per chi interpreta il mostro')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mostri_presenti', to='gestione_plot.quest')),
                ('staffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Interpretato da')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestione_plot.mostrotemplate', verbose_name='Tipo di Mostro')),
            ],
            options={
                'verbose_name': 'Mostro in Quest',
                'verbose_name_plural': '4. Mostri in Quest',
            },
        ),
    ]
