# Generated by Django 5.0.7 on 2026-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0002_mostrotemplate_alter_pngassegnato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='props',
            field=models.TextField(blank=True, null=True, verbose_name='Oggetti di scena / Props'),
        ),
        migrations.AlterField(
            model_name='giornoevento',
            name='sinossi_breve',
            field=models.TextField(),
        ),
    ]
