# Generated by Django 5.0.7 on 2026-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0003_quest_props_alter_giornoevento_sinossi_breve'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostrotemplate',
            name='costume',
            field=models.TextField(blank=True, help_text='Tratti distintivi, maschere o indumenti necessari'),
        ),
    ]
