# Generated by Django 5.0.7 on 2026-01-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0004_mostrotemplate_costume'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornoevento',
            name='descrizione_completa',
            field=models.TextField(blank=True, help_text='Dettagli completi del plot per questo giorno'),
        ),
        migrations.AddField(
            model_name='giornoevento',
            name='titolo',
            field=models.CharField(blank=True, help_text='Titolo identificativo del giorno', max_length=200),
        ),
    ]
