# Generated by Django 5.0.7 on 2026-01-07 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0005_giornoevento_descrizione_completa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='staff_assegnato',
            field=models.ManyToManyField(blank=True, related_name='eventi_gestiti', to=settings.AUTH_USER_MODEL),
        ),
    ]
