# Generated by Django 5.0.7 on 2026-01-11 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0006_alter_evento_staff_assegnato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOffGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compito', models.TextField(help_text='Es: Arbitro, Gestione Audio, Allestimento Zone...')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_offgame', to='gestione_plot.quest')),
                ('staffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Off-Game',
                'verbose_name_plural': '7. Staff Off-Game',
                'unique_together': {('quest', 'staffer')},
            },
        ),
    ]
