# Generated by Django 5.0.7 on 2026-01-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0008_questfase_questtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaRegolamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('contenuto', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='wiki_images/')),
                ('public', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sottopagine', to='gestione_plot.paginaregolamento')),
            ],
            options={
                'ordering': ['ordine', 'titolo'],
            },
        ),
    ]
