# Generated by Django 5.0.7 on 2026-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0009_paginaregolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaregolamento',
            name='visibile_solo_staff',
            field=models.BooleanField(default=False, help_text='Se attivo, la pagina sarà visibile solo a Staff e Superuser, anche se Pubblica è True.', verbose_name='Visibile solo allo Staff'),
        ),
    ]
