# Generated by Django 5.0.7 on 2026-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0010_paginaregolamento_visibile_solo_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaregolamento',
            name='banner_y',
            field=models.IntegerField(default=50, verbose_name='Posizione Verticale Banner (%)'),
        ),
    ]
