# Generated by Django 5.0.7 on 2026-01-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0012_wikiimmagine'),
        ('personaggi', '0101_alter_transazionesospesa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questvista',
            name='cerimoniale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_cerimoniale', to='personaggi.cerimoniale'),
        ),
        migrations.AddField(
            model_name='questvista',
            name='infusione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_infusione', to='personaggi.infusione'),
        ),
        migrations.AddField(
            model_name='questvista',
            name='oggetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_oggetto', to='personaggi.oggetto'),
        ),
        migrations.AddField(
            model_name='questvista',
            name='personaggio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_personaggio', to='personaggi.personaggio'),
        ),
        migrations.AddField(
            model_name='questvista',
            name='tessitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_tessitura', to='personaggi.tessitura'),
        ),
        migrations.AlterField(
            model_name='questvista',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_inventario', to='personaggi.inventario'),
        ),
        migrations.AlterField(
            model_name='questvista',
            name='manifesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questvista_manifesto', to='personaggi.manifesto'),
        ),
        migrations.AlterField(
            model_name='questvista',
            name='tipo',
            field=models.CharField(choices=[('PG', 'Personaggio'), ('PNG', 'Personaggio Non Giocante'), ('INV', 'Inventario'), ('OGG', 'Oggetto'), ('TES', 'Tessitura'), ('INF', 'Infusione'), ('CER', 'Cerimoniale'), ('MAN', 'Manifesto')], max_length=3),
        ),
    ]
