# Generated by Django 5.0.7 on 2026-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0013_questvista_cerimoniale_questvista_infusione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneSito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_associazione', models.CharField(default='KOR35', help_text="Nome dell'associazione", max_length=200)),
                ('descrizione_breve', models.TextField(default="Un'associazione ludico-culturale che organizza eventi di gioco di ruolo dal vivo (GRV/LARP).", help_text="Breve descrizione dell'associazione (2-3 righe)")),
                ('anno_fondazione', models.PositiveIntegerField(default=2020, help_text='Anno di fondazione')),
                ('indirizzo', models.CharField(default='Via Esempio 123', help_text='Indirizzo della sede', max_length=255)),
                ('citta', models.CharField(default='Bolzano', help_text='Città', max_length=100)),
                ('cap', models.CharField(default='39100', help_text='CAP', max_length=10)),
                ('provincia', models.CharField(default='BZ', help_text='Sigla provincia', max_length=2)),
                ('nazione', models.CharField(default='Italia', max_length=50)),
                ('email', models.EmailField(default='info@kor35.it', help_text='Email principale', max_length=254)),
                ('pec', models.EmailField(blank=True, help_text='Email PEC (opzionale)', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Telefono (opzionale)', max_length=50)),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Sito',
                'verbose_name_plural': 'Configurazione Sito',
            },
        ),
        migrations.CreateModel(
            name='LinkSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('email', 'Email'), ('altro', 'Altro')], help_text='Tipo di social/canale', max_length=20)),
                ('nome_visualizzato', models.CharField(help_text='Nome da mostrare (es: @kor35official)', max_length=100)),
                ('url', models.CharField(help_text='URL o link (es: https://instagram.com/kor35)', max_length=500)),
                ('descrizione', models.CharField(blank=True, help_text='Descrizione opzionale', max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione (numero più basso = primo)')),
                ('attivo', models.BooleanField(default=True, help_text='Mostra questo link')),
            ],
            options={
                'verbose_name': 'Link Social',
                'verbose_name_plural': 'Link Social',
                'ordering': ['ordine', 'tipo'],
            },
        ),
    ]
