# Generated by Django 5.0.7 on 2026-04-10 15:30

import social.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_story_publish_and_text_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to=social.models.social_post_media_upload_to),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=social.models.social_post_media_upload_to),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='foto_principale',
            field=models.ImageField(blank=True, null=True, upload_to=social.models.social_profile_image_upload_to),
        ),
        migrations.AlterField(
            model_name='socialstory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialstory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=social.models.social_story_media_upload_to),
        ),
        migrations.AlterField(
            model_name='socialstory',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstoryhighlight',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstoryhighlightitem',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstoryreaction',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstoryreply',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstorytag',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialstoryview',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
