# Allinea lo state delle migrazioni ai modelli (drift segnalato a ogni deploy).

# Generated by Django 5.0.7 on 2026-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_rubricaarticoloimmagine_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcommentlike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
