# Generated by Django 5.0.7 on 2025-10-17 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
