# Generated by Django 5.0.7 on 2025-10-26 17:05

import django.db.models.deletion
import oggetti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaggi', '0012_spell_aura'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_vista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('testo', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oggetti.a_vista')),
            ],
            bases=('oggetti.a_vista',),
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.CharField(default=oggetti.models.generate_short_id, editable=False, max_length=14, primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('testo', models.TextField(blank=True, null=True)),
                ('vista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oggetti.a_vista')),
            ],
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oggetti.a_vista')),
                ('aura', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oggetti_aura', to='personaggi.punteggio', verbose_name='Aura associata')),
                ('elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, to='personaggi.punteggio', verbose_name='Elementi associati')),
            ],
            bases=('oggetti.a_vista',),
        ),
    ]
