# Generated by Django 5.0.7 on 2025-11-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oggetti', '0001_initial'),
        ('personaggi', '0013_statistica_abilitastatistica_abilita_statistiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='OggettoStatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField(default=0)),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oggetti.oggetto')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'unique_together': {('oggetto', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='oggetto',
            name='statistiche',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche', through='oggetti.OggettoStatistica', to='personaggi.statistica', verbose_name='Statistiche modificate'),
        ),
    ]
