# Generated by Django 5.0.7 on 2025-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oggetti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='testo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
