# Generated by Django 5.0.7 on 2025-10-26 16:21

import django.db.models.deletion
import oggetti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oggetti', '0002_qrcode_testo'),
        ('personaggi', '0011_alter_abilita_tier_options_abilita_tier_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='id',
            field=models.CharField(default=oggetti.models.generate_short_id, editable=False, max_length=14, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('testo', models.TextField(blank=True, null=True)),
                ('aura', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oggetti_aura', to='personaggi.punteggio', verbose_name='Aura associata')),
                ('elementi', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'EL'}, to='personaggi.punteggio', verbose_name='Elementi associati')),
            ],
            options={
                'ordering': ['-data_creazione'],
                'abstract': False,
            },
        ),
    ]
