# Generated by Django 5.0.7 on 2025-11-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oggetti', '0002_oggettostatistica_oggetto_statistiche'),
        ('personaggi', '0015_statistica_valore_base_predefinito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attivata',
            fields=[
                ('a_vista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oggetti.a_vista')),
            ],
            bases=('oggetti.a_vista',),
        ),
        migrations.CreateModel(
            name='AttivataElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oggetti.attivata')),
                ('elemento', models.ForeignKey(limit_choices_to={'tipo': 'EL'}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.punteggio', verbose_name='Elemento')),
            ],
        ),
        migrations.AddField(
            model_name='attivata',
            name='elementi',
            field=models.ManyToManyField(blank=True, through='oggetti.AttivataElemento', to='personaggi.punteggio', verbose_name='Elementi associati'),
        ),
        migrations.CreateModel(
            name='AttivataStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('attivata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oggetti.attivata')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Statistica (Valore Base)',
                'verbose_name_plural': 'Statistiche (Valori Base)',
                'unique_together': {('attivata', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='attivata',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='attivata_statistiche_base', through='oggetti.AttivataStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
        migrations.CreateModel(
            name='OggettoStatisticaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_base', models.IntegerField(default=0)),
                ('oggetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oggetti.oggetto')),
                ('statistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaggi.statistica')),
            ],
            options={
                'verbose_name': 'Statistica (Valore Base)',
                'verbose_name_plural': 'Statistiche (Valori Base)',
                'unique_together': {('oggetto', 'statistica')},
            },
        ),
        migrations.AddField(
            model_name='oggetto',
            name='statistiche_base',
            field=models.ManyToManyField(blank=True, related_name='oggetti_statistiche_base', through='oggetti.OggettoStatisticaBase', to='personaggi.statistica', verbose_name='Statistiche (Valori Base)'),
        ),
    ]
