# Generated by Django 5.0.7 on 2026-01-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaggi', '0090_punteggio_stat_costo_invio_proposta_cerimoniale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('pc_guadagnati', models.PositiveIntegerField(default=0, help_text='PC assegnati ai partecipanti')),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('sinossi', models.TextField(blank=True)),
                ('luogo', models.CharField(blank=True, max_length=255)),
                ('partecipanti', models.ManyToManyField(blank=True, related_name='eventi_partecipati', to=settings.AUTH_USER_MODEL)),
                ('staff_assegnato', models.ManyToManyField(help_text='Tutti gli admin e gli staffer coinvolti', related_name='eventi_gestiti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': '1. Eventi',
            },
        ),
        migrations.CreateModel(
            name='GiornoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora_inizio', models.DateTimeField()),
                ('data_ora_fine', models.DateTimeField()),
                ('sinossi_breve', models.TextField(max_length=500)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giorni', to='gestione_plot.evento')),
            ],
            options={
                'verbose_name': 'Giorno Evento',
                'verbose_name_plural': '2. Giorni Evento',
                'ordering': ['data_ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione_ampia', models.TextField()),
                ('orario_indicativo', models.TimeField()),
                ('mostri_generici', models.JSONField(blank=True, default=dict, help_text="Esempio: {'Zombie': 3, 'Guardie': 2}")),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='gestione_plot.giornoevento')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': '3. Quests',
                'ordering': ['orario_indicativo'],
            },
        ),
        migrations.CreateModel(
            name='PngAssegnato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine_uscita', models.PositiveIntegerField(default=1, help_text="Determina l'ordine se uno staffer ha più PnG nella stessa quest")),
                ('personaggio', models.ForeignKey(limit_choices_to={'is_png': True}, on_delete=django.db.models.deletion.CASCADE, to='personaggi.personaggio')),
                ('staffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='png_richiesti', to='gestione_plot.quest')),
            ],
            options={
                'verbose_name': 'PnG Assegnato',
                'verbose_name_plural': '4. PnG Assegnati',
                'ordering': ['staffer', 'ordine_uscita'],
            },
        ),
        migrations.CreateModel(
            name='QuestVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INV', 'Inventario (Collection)'), ('MAN', 'Manifesto (Messaggio)')], max_length=3)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.inventario')),
                ('manifesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.manifesto')),
                ('qr_code', models.OneToOneField(blank=True, help_text='Il QR associato tramite scansione in fase di setup', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.qrcode')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viste_previste', to='gestione_plot.quest')),
            ],
            options={
                'verbose_name': 'Oggetto Vista Quest',
                'verbose_name_plural': '5. Oggetti Vista',
            },
        ),
    ]
