# Generated by Django 5.0.7 on 2026-01-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0007_staffoffgame'),
        ('personaggi', '0092_alter_abilita_requisito_requisito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=1)),
                ('titolo', models.CharField(help_text='Es: Scena del crimine, Assalto...', max_length=100)),
                ('descrizione', models.TextField(blank=True, help_text='Cosa succede in questa fase')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi', to='gestione_plot.quest')),
            ],
            options={
                'verbose_name': 'Fase Quest',
                'verbose_name_plural': '3b. Fasi Quest',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='QuestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('PNG', 'PnG'), ('MOSTRO', 'Mostro'), ('OFF', 'Staff Off-Game')], max_length=10)),
                ('compito_offgame', models.CharField(blank=True, choices=[('REG', 'Regole'), ('AIU', 'Aiuto'), ('ALL', 'Allestimento')], help_text='Se Staff Off-Game', max_length=10, null=True)),
                ('punti_vita', models.IntegerField(default=1)),
                ('armatura', models.IntegerField(default=0)),
                ('guscio', models.IntegerField(default=0)),
                ('istruzioni', models.TextField(blank=True, help_text='Istruzioni specifiche per lo staffer')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gestione_plot.questfase')),
                ('mostro_template', models.ForeignKey(blank=True, help_text='Se Mostro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_plot.mostrotemplate')),
                ('personaggio', models.ForeignKey(blank=True, help_text='Se PnG', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personaggi.personaggio')),
                ('staffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assegnati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Staff',
                'verbose_name_plural': '3c. Task Staff',
            },
        ),
    ]
