# Generated by Django 5.0.7 on 2026-01-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0011_paginaregolamento_banner_y'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text="Titolo descrittivo dell'immagine", max_length=200)),
                ('descrizione', models.TextField(blank=True, help_text="Descrizione opzionale dell'immagine")),
                ('immagine', models.ImageField(help_text='Immagine da caricare', upload_to='wiki_images/widgets/')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('larghezza_max', models.PositiveIntegerField(default=800, help_text='Larghezza massima in pixel (0 = dimensione originale)')),
                ('allineamento', models.CharField(choices=[('left', 'Sinistra'), ('center', 'Centro'), ('right', 'Destra'), ('full', 'Larghezza piena')], default='center', help_text="Allineamento dell'immagine nel contenuto", max_length=10)),
                ('creatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immagini_wiki_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Immagine Wiki',
                'verbose_name_plural': 'Immagini Wiki',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
