# Generated by Django 5.0.7 on 2026-02-13 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0014_configurazionesito_linksocial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiButtonWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Titolo opzionale del widget (per identificazione interna)', max_length=200)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('creatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='button_widgets_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget Pulsanti',
                'verbose_name_plural': 'Widget Pulsanti',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='WikiButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titolo del pulsante', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descrizione (opzionale)', max_length=200)),
                ('subtext', models.CharField(blank=True, help_text='Testo secondario (solo per stile gradiente)', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Nome icona Lucide (es: Sparkles, BookOpen)', max_length=50)),
                ('style', models.CharField(choices=[('gradient', 'Gradiente (grande)'), ('light', 'Chiaro (compatto)')], default='gradient', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Piccolo'), ('medium', 'Medio'), ('large', 'Grande')], default='medium', max_length=20)),
                ('color_preset', models.CharField(choices=[('indigo_purple', 'Indaco-Viola'), ('red_orange', 'Rosso-Arancio'), ('emerald_teal', 'Smeraldo-Verde Acqua'), ('blue_indigo', 'Blu-Indaco'), ('pink_rose', 'Rosa'), ('amber_orange', 'Ambra-Arancio'), ('cyan_blue', 'Ciano-Blu'), ('violet_purple', 'Viola-Porpora'), ('slate_gray', 'Ardesia-Grigio'), ('lime_green', 'Lime-Verde')], default='indigo_purple', max_length=30)),
                ('link_type', models.CharField(choices=[('wiki', 'Pagina Wiki'), ('app', 'Sezione App')], default='wiki', max_length=10)),
                ('wiki_slug', models.CharField(blank=True, help_text='Slug della pagina wiki di destinazione', max_length=200)),
                ('app_route', models.CharField(blank=True, help_text='Percorso della sezione app (es: /app)', max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='gestione_plot.wikibuttonwidget')),
            ],
            options={
                'verbose_name': 'Pulsante',
                'verbose_name_plural': 'Pulsanti',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
