# Generated by Django 5.0.7 on 2026-10-07 10:24
# Allinea lo state delle migrazioni ai modelli (drift segnalato a ogni deploy).

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_plot', '0054_missioneevento_attiva'),
        ('personaggi', '0297_sync_model_state_deploy'),
    ]

    operations = [
        # Su Postgres il UniqueConstraint condizionale è un INDEX, non un CONSTRAINT.
        # L'indice esiste già (da 0034): aggiorniamo solo lo state Django
        # (ordine dei termini in Q) senza DROP/CREATE sul DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='creazioneguidataflusso',
                    name='uniq_sandbox_test_per_produzione',
                ),
                migrations.AddConstraint(
                    model_name='creazioneguidataflusso',
                    constraint=models.UniqueConstraint(
                        condition=models.Q(('flusso_produzione__isnull', False), ('modalita_test', True)),
                        fields=('flusso_produzione',),
                        name='uniq_sandbox_test_per_produzione',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RenameIndex(
            model_name='staffcompitoassegnazione',
            new_name='gestione_pl_user_id_b1f892_idx',
            old_name='gestione_pl_user_id_c0a91e_idx',
        ),
        migrations.RenameIndex(
            model_name='staffcompitoassegnazione',
            new_name='gestione_pl_compito_03bf6c_idx',
            old_name='gestione_pl_compito_2b4c11_idx',
        ),
        migrations.AlterField(
            model_name='creazioneguidataflusso',
            name='campagna',
            field=models.ForeignKey(blank=True, help_text='Se vuoto, il flusso vale per tutte le campagne (priorità inferiore rispetto a flussi specifici).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flussi_creazione_guidata', to='personaggi.campagna'),
        ),
        migrations.AlterField(
            model_name='creazioneguidatapasso',
            name='opzioni_ui',
            field=models.JSONField(blank=True, default=dict, help_text='presentazione: pulsanti|si_no|radio; gruppo_id; modalita_rewind: ramo|toggle; widget_fondo: {tipo: modello_aura, ...}'),
        ),
        migrations.AlterField(
            model_name='eventotrasferimentodeposito',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='linksocial',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('whatsapp_cambusa', 'WhatsApp — La Cambusa'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('email', 'Email'), ('altro', 'Altro')], help_text='Tipo di social/canale', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualepdf',
            name='attivo',
            field=models.BooleanField(default=True, help_text='Se disattivo, non compare nella homepage pubblica.'),
        ),
    ]
